<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 18 Generalized Additive Model | BIOSTATS</title>
<meta name="author" content="Akira Terui">
<meta name="description" content="In generalized linear models (GLMs) and generalized linear mixed models (GLMMs), a key structural assumption is linearity on the scale of the linear predictor. That is, after applying the link...">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="Chapter 18 Generalized Additive Model | BIOSTATS">
<meta property="og:type" content="book">
<meta property="og:description" content="In generalized linear models (GLMs) and generalized linear mixed models (GLMMs), a key structural assumption is linearity on the scale of the linear predictor. That is, after applying the link...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 18 Generalized Additive Model | BIOSTATS">
<meta name="twitter:description" content="In generalized linear models (GLMs) and generalized linear mixed models (GLMMs), a key structural assumption is linearity on the scale of the linear predictor. That is, after applying the link...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-QZSNHVQQNV"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-QZSNHVQQNV');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BIOSTATS</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Introduction</a></li>
<li class="book-part">Getting Started</li>
<li><a class="" href="what-is-r-and-r-studio.html"><span class="header-section-number">1</span> What is R and R studio?</a></li>
<li><a class="" href="installing-r-and-rstudio.html"><span class="header-section-number">2</span> Installing R and RStudio</a></li>
<li><a class="" href="r-project.html"><span class="header-section-number">3</span> R Project</a></li>
<li class="book-part">R Basics</li>
<li><a class="" href="data-structure.html"><span class="header-section-number">4</span> Data Structure</a></li>
<li><a class="" href="data-manipulation.html"><span class="header-section-number">5</span> Data Manipulation</a></li>
<li><a class="" href="visualization.html"><span class="header-section-number">6</span> Visualization</a></li>
<li class="book-part">Basic Statistics</li>
<li><a class="" href="descriptive-statistics.html"><span class="header-section-number">7</span> Descriptive Statistics</a></li>
<li><a class="" href="sampling.html"><span class="header-section-number">8</span> Sampling</a></li>
<li><a class="" href="probabilistic-view.html"><span class="header-section-number">9</span> Probabilistic View</a></li>
<li><a class="" href="two-group-comparison.html"><span class="header-section-number">10</span> Two-Group Comparison</a></li>
<li><a class="" href="multiple-group-comparison.html"><span class="header-section-number">11</span> Multiple-Group Comparison</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">12</span> Regression</a></li>
<li><a class="" href="linear-model.html"><span class="header-section-number">13</span> Linear Model</a></li>
<li><a class="" href="generalized-linear-model.html"><span class="header-section-number">14</span> Generalized Linear Model</a></li>
<li><a class="" href="likelihood.html"><span class="header-section-number">15</span> Likelihood</a></li>
<li><a class="" href="model-comparison.html"><span class="header-section-number">16</span> Model Comparison</a></li>
<li class="book-part">Applied Statistics</li>
<li><a class="" href="generalized-linear-mixed-effect-model.html"><span class="header-section-number">17</span> Generalized Linear Mixed Effect Model</a></li>
<li><a class="active" href="generalized-additive-model.html"><span class="header-section-number">18</span> Generalized Additive Model</a></li>
<li><a class="" href="unconstrained-ordination.html"><span class="header-section-number">19</span> Unconstrained Ordination</a></li>
<li><a class="" href="constrained-ordination.html"><span class="header-section-number">20</span> Constrained Ordination</a></li>
<li><a class="" href="structural-equation-modeling.html"><span class="header-section-number">21</span> Structural Equation Modeling</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="git-github.html">Git &amp; GitHub</a></li>
<li><a class="" href="base-plot.html">Base Plot</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/aterui/biostats">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="generalized-additive-model" class="section level1" number="18">
<h1>
<span class="header-section-number">18</span> Generalized Additive Model<a class="anchor" aria-label="anchor" href="#generalized-additive-model"><i class="fas fa-link"></i></a>
</h1>
<p>In generalized linear models (GLMs) and generalized linear mixed models (GLMMs), a key structural assumption is <strong>linearity on the scale of the linear predictor</strong>. That is, after applying the link function, the expected value of the response is assumed to be a linear combination of predictors and their associated parameters.</p>
<p>In biological and ecological data, however, relationships are often <strong>nonlinear but smooth</strong>, reflecting processes such as seasonality, thresholds, saturation, or diminishing returns. When these patterns are forced into a strictly linear framework, GLMs and GLMMs may yield biased parameter estimates, poor predictive performance, or misleading inference.</p>
<p>To address these limitations, this chapter introduces <strong>generalized additive models (GAMs)</strong>, which extend GLMs by allowing predictors to enter the model as smooth functions rather than assuming linear effects.</p>
<p>Learning Objectives:</p>
<ul>
<li><p>Understand the linearity assumptions underlying GLMs and GLMMs</p></li>
<li><p>Understand how smoothing functions relax these assumptions</p></li>
<li><p>Evaluate the advantages and limitations of additive models</p></li>
</ul>
<div class="sourceCode" id="cb501"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>,</span>
<span>               <span class="va">ggeffects</span>,</span>
<span>               <span class="va">mgcv</span><span class="op">)</span></span></code></pre></div>
<div id="seasonal-data" class="section level2" number="18.1">
<h2>
<span class="header-section-number">18.1</span> Seasonal Data<a class="anchor" aria-label="anchor" href="#seasonal-data"><i class="fas fa-link"></i></a>
</h2>
<div id="water-temperature-example" class="section level3" number="18.1.1">
<h3>
<span class="header-section-number">18.1.1</span> Water temperature example<a class="anchor" aria-label="anchor" href="#water-temperature-example"><i class="fas fa-link"></i></a>
</h3>
<p>To illustrate the application of nonlinear models, we use water temperature data collected from artificial wetlands on the campus of the University of North Carolina, Greensboro. These data are publicly available and form part of <a href="https://www.sciencedirect.com/science/article/pii/S2351989425002252">Ibrahim <em>et al.</em> 2025</a>.</p>
<div class="sourceCode" id="cb502"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">link</span> <span class="op">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/aterui/biostats/master/data_raw/data_water_temp.csv"</span></span>
<span></span>
<span><span class="op">(</span><span class="va">df_wt_raw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">link</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 77,596 × 4
##       id date_time       temp site 
##    &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;
##  1     1 8/6/2021 18:00  23.1 woody
##  2     2 8/6/2021 18:15  23.1 woody
##  3     3 8/6/2021 18:30  23.1 woody
##  4     4 8/6/2021 18:45  23.2 woody
##  5     5 8/6/2021 19:00  23.2 woody
##  6     6 8/6/2021 19:15  23.2 woody
##  7     7 8/6/2021 19:30  23.2 woody
##  8     8 8/6/2021 19:45  23.2 woody
##  9     9 8/6/2021 20:00  23.2 woody
## 10    10 8/6/2021 20:15  23.3 woody
## # ℹ 77,586 more rows</code></pre>
<p>The dataset loaded from the provided link contains water temperature observations from wetlands and includes three main columns. The <code>date_time</code> column records the timestamp of each measurement, typically in month/day/year format. The <code>site</code> column indicates the wetland type or location (e.g., “woody” vs. “open”), serving as a factor to distinguish between different wetland types. Finally, the <code>temp</code> column provides the numeric water temperature in degrees Celsius, which can be used as the response variable in statistical models.</p>
<p>It is always a good practice to begin by checking the class of each column, as misunderstanding data types can lead to unnecessary confusion during data analysis.</p>
<div class="sourceCode" id="cb504"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">df_wt_raw</span>, <span class="va">class</span><span class="op">)</span></span></code></pre></div>
<pre><code>##          id   date_time        temp        site 
##   "numeric" "character"   "numeric" "character"</code></pre>
<p>A potential issue in this dataset is that the <code>date_time</code> column is stored as a “<strong>character</strong>.” Although <code>data_time</code> contains temporal information, the character data type does not allow R to interpret it as a date. In the following code, we will convert this column to a <code>Date</code> object, which explicitly encodes temporal information and enables time-based operations.</p>
<div class="sourceCode" id="cb506"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Start from the raw water-temperature dataset</span></span>
<span><span class="op">(</span><span class="va">df_wt</span> <span class="op">&lt;-</span> <span class="va">df_wt_raw</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># Convert the character datetime column into a Date object.</span></span>
<span>    <span class="co"># The format argument specifies month/day/year.</span></span>
<span>    date <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="va">date_time</span>,</span>
<span>                   format <span class="op">=</span> <span class="st">"%m/%d/%Y"</span><span class="op">)</span>,</span>
<span>    <span class="co"># Extract the calendar year from the Date object</span></span>
<span>    year <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/year.html">year</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span>,</span>
<span>    <span class="co"># Extract the month (1–12) from the Date object</span></span>
<span>    month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="co"># Subset the data to observations from the year 2022 only</span></span>
<span>  <span class="co"># March through October</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">2022</span>,</span>
<span>         <span class="fu"><a href="https://dplyr.tidyverse.org/reference/between.html">between</a></span><span class="op">(</span><span class="va">month</span>, <span class="fl">3</span>, <span class="fl">10</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 35,287 × 7
##       id date_time      temp site  date        year month
##    &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt; &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 19801 3/1/2022 0:00  7.67 woody 2022-03-01  2022     3
##  2 19802 3/1/2022 0:15  7.62 woody 2022-03-01  2022     3
##  3 19803 3/1/2022 0:30  7.57 woody 2022-03-01  2022     3
##  4 19804 3/1/2022 0:45  7.52 woody 2022-03-01  2022     3
##  5 19805 3/1/2022 1:00  7.44 woody 2022-03-01  2022     3
##  6 19806 3/1/2022 1:15  7.39 woody 2022-03-01  2022     3
##  7 19807 3/1/2022 1:30  7.34 woody 2022-03-01  2022     3
##  8 19808 3/1/2022 1:45  7.29 woody 2022-03-01  2022     3
##  9 19809 3/1/2022 2:00  7.27 woody 2022-03-01  2022     3
## 10 19810 3/1/2022 2:15  7.22 woody 2022-03-01  2022     3
## # ℹ 35,277 more rows</code></pre>
<p>In the example above, we restricted the dataset to the period from 2022-03-01 to 2022-10-31 because the woody site contains missing data outside this range. Next, we aggregate the data to daily means because the original measurements were recorded at 15-minute intervals, which is too fine-grained for our analysis.</p>
<div class="sourceCode" id="cb508"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Aggregate raw water temperature data to daily averages</span></span>
<span><span class="va">df_wt_daily</span> <span class="op">&lt;-</span> <span class="va">df_wt</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="co"># Group the data by date and site</span></span>
<span>  <span class="co"># This ensures that averaging is done separately for each site on each day</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">date</span>, <span class="va">site</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="co"># Compute summary statistics for each group</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span></span>
<span>    <span class="co"># Take the mean of the 'temp' column within each group</span></span>
<span>    <span class="co"># na.rm = TRUE ignores missing values (NA) in the calculation</span></span>
<span>    <span class="co"># round(..., 3) rounds the resulting mean to 3 decimal places</span></span>
<span>    temp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">temp</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<p>Since water temperature is seasonal, it rises from spring to summer and falls from summer to fall. These data are collected from two wetlands, and colors distinguish different types of wetlands.</p>
<div class="sourceCode" id="cb509"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Visualize daily water temperature for each wetland site</span></span>
<span><span class="va">df_wt_daily</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">date</span>,      <span class="co"># Date on the x-axis</span></span>
<span>    y <span class="op">=</span> <span class="va">temp</span>,      <span class="co"># Daily averaged temperature on the y-axis</span></span>
<span>    color <span class="op">=</span> <span class="va">site</span>   <span class="co"># Color points by wetland type (woody vs open)</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add points for each observation</span></span>
<span>  <span class="co"># alpha = 0.25 makes points semi-transparent to reduce overplotting</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Apply a clean black-and-white theme for readability</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Customize axis labels and legend title</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Date"</span>,                <span class="co"># x-axis label</span></span>
<span>    y <span class="op">=</span> <span class="st">"Water Temperature"</span>,   <span class="co"># y-axis label</span></span>
<span>    color <span class="op">=</span> <span class="st">"Wetland Type"</span>     <span class="co"># legend title for the color mapping</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:gam-plot-water-temp"></span>
<img src="biostats_files/figure-html/gam-plot-water-temp-1.png" alt="Daily water temperature measured in two types of artificial wetlands (“woody” and “open”) on the UNCG campus. Each point represents the daily average temperature, with semi-transparent points to reduce overplotting. Colors indicate wetland type, and the x-axis shows the date over the monitoring period." width="672"><p class="caption">
Figure 18.1: Daily water temperature measured in two types of artificial wetlands (“woody” and “open”) on the UNCG campus. Each point represents the daily average temperature, with semi-transparent points to reduce overplotting. Colors indicate wetland type, and the x-axis shows the date over the monitoring period.
</p>
</div>
<p>What happens if we model this seasonal dataset using a linear model? We can explore this using the <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> (or <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>) function, and visualizing the predicted values will highlight the limitations of treating inherently seasonal data as linear.</p>
<div class="sourceCode" id="cb510"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Add new variables and ensure proper data types</span></span>
<span><span class="va">df_wt_daily</span> <span class="op">&lt;-</span> <span class="va">df_wt_daily</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># Convert the date column to Julian day (day of year)</span></span>
<span>    <span class="co"># Useful for modeling seasonal trends</span></span>
<span>    j_date <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/day.html">yday</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span>,</span>
<span>    <span class="co"># Ensure 'site' is treated as a factor (categorical variable)</span></span>
<span>    site <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">site</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit a Generalized Linear Model (GLM) with Gaussian family</span></span>
<span><span class="va">m_glm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span></span>
<span>  <span class="va">temp</span> <span class="op">~</span> <span class="va">j_date</span> <span class="op">+</span> <span class="va">site</span>,  <span class="co"># Model daily temperature as a function of Julian day and wetland site</span></span>
<span>  data <span class="op">=</span> <span class="va">df_wt_daily</span>,    <span class="co"># Dataset to use</span></span>
<span>  family <span class="op">=</span> <span class="st">"gaussian"</span>    <span class="co"># Specify Gaussian distribution (standard linear regression)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_glm</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = temp ~ j_date + site, family = "gaussian", data = df_wt_daily)
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 15.165281   0.688730  22.019  &lt; 2e-16 ***
## j_date       0.021495   0.003316   6.481 2.23e-10 ***
## sitewoody   -0.640290   0.469106  -1.365    0.173    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for gaussian family taken to be 26.95744)
## 
##     Null deviance: 14311  on 489  degrees of freedom
## Residual deviance: 13128  on 487  degrees of freedom
## AIC: 3009.7
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>The model suggests that water temperature increases with Julian date and that there is no significant difference between wetland types. However, this conclusion may be misleading because of the strong seasonal (nonlinear) pattern in the data. Visualizing the model-predicted values can help assess this result.</p>
<p>The <code>ggpredict()</code> function from the <code>ggeffects</code> package provides a convenient way to generate predicted values from a model, internally using the base <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function. Factor variables (e.g., <code>site</code>) are returned as <code>group</code>, while continuous variables are returned as <code>x</code>; these can then be renamed to match the original column names for clarity.</p>
<div class="sourceCode" id="cb512"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Generate model predictions across all Julian days and wetland sites</span></span>
<span><span class="va">df_pred</span> <span class="op">&lt;-</span> <span class="fu">ggpredict</span><span class="op">(</span><span class="va">m_glm</span>,</span>
<span>                     terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>                       <span class="st">"j_date [all]"</span>,  <span class="co"># Use all observed values of Julian day</span></span>
<span>                       <span class="st">"site [all]"</span>     <span class="co"># Generate predictions for all levels of the factor 'site'</span></span>
<span>                     <span class="op">)</span></span>
<span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="co"># Rename the default columns to match the original dataset</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>site <span class="op">=</span> <span class="va">group</span>,  <span class="co"># 'group' from ggpredict() corresponds to the factor variable 'site'</span></span>
<span>         j_date <span class="op">=</span> <span class="va">x</span>     <span class="co"># 'x' from ggpredict() corresponds to the predictor 'j_date'</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot daily water temperature and overlay model predictions</span></span>
<span><span class="va">df_wt_daily</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">j_date</span>,   <span class="co"># Julian day on x-axis</span></span>
<span>    y <span class="op">=</span> <span class="va">temp</span>,     <span class="co"># Observed daily temperature on y-axis</span></span>
<span>    color <span class="op">=</span> <span class="va">site</span>  <span class="co"># Color points by wetland type (factor)</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Overlay predicted values from the model</span></span>
<span>  <span class="co"># df_pred contains predictions from ggpredict()</span></span>
<span>  <span class="co"># aes(y = predicted) maps the model's predicted temperature to y</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_pred</span>,</span>
<span>            <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">predicted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Julian Date"</span>,         <span class="co"># x-axis label</span></span>
<span>       y <span class="op">=</span> <span class="st">"Water Temperature"</span>,   <span class="co"># y-axis label</span></span>
<span>       color <span class="op">=</span> <span class="st">"Wetland Type"</span>     <span class="co"># Legend title for site color</span></span>
<span>       <span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:gam-plot-linear"></span>
<img src="biostats_files/figure-html/gam-plot-linear-1.png" alt="Daily water temperature in two types of artificial wetlands (“woody” and “open”) is shown as points, with semi-transparent markers to reduce overplotting. The overlaid lines represent predicted values from a linear model (glm) using Julian day and site as predictors. The plot highlights a clear mismatch between the observed seasonal fluctuations and the linear predictions, illustrating the limitations of modeling inherently seasonal data with a linear approach." width="672"><p class="caption">
Figure 18.2: Daily water temperature in two types of artificial wetlands (“woody” and “open”) is shown as points, with semi-transparent markers to reduce overplotting. The overlaid lines represent predicted values from a linear model (glm) using Julian day and site as predictors. The plot highlights a clear mismatch between the observed seasonal fluctuations and the linear predictions, illustrating the limitations of modeling inherently seasonal data with a linear approach.
</p>
</div>
</div>
<div id="smooth-function" class="section level3" number="18.1.2">
<h3>
<span class="header-section-number">18.1.2</span> Smooth function<a class="anchor" aria-label="anchor" href="#smooth-function"><i class="fas fa-link"></i></a>
</h3>
<p>Linear models assume a straight-line relationship between predictors and the response. For seasonal data, like water temperature over a year, this assumption is often violated: temperatures rise in spring, peak in summer, and fall in autumn—a nonlinear pattern that a simple linear term cannot capture.</p>
<p>A Generalized Additive Model (GAM) extends linear models by replacing (one or more of) linear terms with <strong>smooth functions</strong>, allowing the relationship to bend and flex according to the data:</p>
<p><span class="math display">\[
y_i = \alpha + f(x) + \varepsilon_i
\]</span></p>
<p>Here, <span class="math inline">\(f(\cdot)\)</span> is a <strong>smooth function</strong> estimated from the data, often using <strong>splines</strong>. In practice, this means GAMs can model seasonal or other nonlinear trends without needing to specify the exact form of the curve in advance.</p>
<p>In R, we can use the <code>mgcv</code> package to implement this approach. We apply a smooth function <code>s()</code> to <code>j_date</code> to capture the clear seasonal pattern, while keeping <code>site</code> (wetland type) as a linear term, since we do not expect the effect of wetland type to vary nonlinearly.</p>
<div class="sourceCode" id="cb513"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m_gam</span> <span class="op">&lt;-</span> <span class="fu">gam</span><span class="op">(</span><span class="va">temp</span> <span class="op">~</span> <span class="va">site</span> <span class="op">+</span> <span class="fu">s</span><span class="op">(</span><span class="va">j_date</span><span class="op">)</span>,</span>
<span>             data <span class="op">=</span> <span class="va">df_wt_daily</span>,</span>
<span>             family <span class="op">=</span> <span class="st">"gaussian"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_gam</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## temp ~ site + s(j_date)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  19.0774     0.1157 164.878  &lt; 2e-16 ***
## sitewoody    -0.6403     0.1636  -3.913 0.000104 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##             edf Ref.df     F p-value    
## s(j_date) 8.617  8.958 431.1  &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  0.888   Deviance explained =   89%
## GCV = 3.3527  Scale est. = 3.28      n = 490</code></pre>
<p>The interpretation of the parametric coefficients is largely the same as in GLMs or GLMMs. In this case, the effect of site (wetland type) becomes statistically significant. This occurs because the nonlinear seasonal pattern is modeled first through the smooth term, allowing the <code>site</code> effect to be assessed without being confounded by seasonal structure in the data.</p>
<p>The smooth term <code>s(j_date)</code> in the GAM captures the nonlinear seasonal variation in water temperature across the year. Its <strong>effective degrees of freedom</strong> (edf =8.62) indicate that the relationship is flexible rather than a straight line, allowing the model to follow the rise of temperature in spring, the peak in summer, and the decline in fall. The <code>edf</code> becomes approximately 1 when the smooth term represents an essentially linear effect - if this occurs, adding a predictor as a smooth term is not meaningful.</p>
<p>The extremely low p-value (&lt;2e-16) shows that this seasonal pattern is highly significant, meaning that the smooth term explains a large portion of the variation in temperature that a linear term alone could not capture.</p>
<p>The GCV (generalized cross-validation) score (3.35) is worth mentioning because it is used to determine how wiggly the curve should be. A lower GCV indicates a better balance between model fit and smoothness, penalizing excessive curvature to avoid overfitting.</p>
<p>The <code>ggpredict()</code> function allows us to generate and visualize predicted values from a GAM.</p>
<div class="sourceCode" id="cb515"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_pred_gam</span> <span class="op">&lt;-</span> <span class="fu">ggpredict</span><span class="op">(</span><span class="va">m_gam</span>,</span>
<span>                         terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>                           <span class="st">"j_date [all]"</span>, </span>
<span>                           <span class="st">"site [all]"</span><span class="op">)</span></span>
<span>                         <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>site <span class="op">=</span> <span class="va">group</span>,</span>
<span>         j_date <span class="op">=</span> <span class="va">x</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_wt_daily</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">j_date</span>,</span>
<span>    y <span class="op">=</span> <span class="va">temp</span>, </span>
<span>    color <span class="op">=</span> <span class="va">site</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Overlay predicted values from the GAM</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_pred_gam</span>,</span>
<span>            <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">predicted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Julian Date"</span>,         <span class="co"># x-axis label</span></span>
<span>       y <span class="op">=</span> <span class="st">"Water Temperature"</span>,   <span class="co"># y-axis label</span></span>
<span>       color <span class="op">=</span> <span class="st">"Wetland Type"</span>     <span class="co"># Legend title for site color</span></span>
<span>       <span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:gam-plot-smooth"></span>
<img src="biostats_files/figure-html/gam-plot-smooth-1.png" alt="Daily water temperature in two types of artificial wetlands (“woody” and “open”) is shown as points, with semi-transparent markers to reduce overplotting. The overlaid lines represent predicted values from a linear model (glm) using Julian day and site as predictors. The plot highlights a clear mismatch between the observed seasonal fluctuations and the linear predictions, illustrating the limitations of modeling inherently seasonal data with a linear approach." width="672"><p class="caption">
Figure 18.3: Daily water temperature in two types of artificial wetlands (“woody” and “open”) is shown as points, with semi-transparent markers to reduce overplotting. The overlaid lines represent predicted values from a linear model (glm) using Julian day and site as predictors. The plot highlights a clear mismatch between the observed seasonal fluctuations and the linear predictions, illustrating the limitations of modeling inherently seasonal data with a linear approach.
</p>
</div>
<p>Key insights for practical use:</p>
<ul>
<li>Smooth terms (<code>s(x)</code>) allow flexible, data-driven curves.</li>
<li>The model automatically balances fit vs. smoothness to avoid overfitting.</li>
<li>Categorical or other continuous predictors can be included as linear predictors alongside smooth terms.</li>
</ul>
<p>This GAM framework lets you move from linear approximations to flexible, realistic modeling of seasonal patterns, which can then be illustrated with a simple water temperature example before diving into mathematical details.</p>
</div>
</div>
<div id="estimating-smoothness" class="section level2" number="18.2">
<h2>
<span class="header-section-number">18.2</span> Estimating Smoothness<a class="anchor" aria-label="anchor" href="#estimating-smoothness"><i class="fas fa-link"></i></a>
</h2>
<div id="choice-of-smooth-function" class="section level3" number="18.2.1">
<h3>
<span class="header-section-number">18.2.1</span> Choice of smooth function<a class="anchor" aria-label="anchor" href="#choice-of-smooth-function"><i class="fas fa-link"></i></a>
</h3>
<p>By default, <code><a href="https://rdrr.io/pkg/mgcv/man/s.html">mgcv::s()</a></code> employs <strong>thin plate regression splines</strong> as a smoothing function. While this is one of the most broadly applicable approaches, other options may be more appropriate depending on the structure of your data. The following table summarizes the possible alternatives offered in the <code>mgcv</code> package, along with their typical applications.</p>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<colgroup>
<col width="23%">
<col width="23%">
<col width="23%">
<col width="30%">
</colgroup>
<thead><tr class="header">
<th>Smoother / Option</th>
<th>How to Specify</th>
<th>Description</th>
<th>Typical Use Case / Notes</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Thin plate regression spline (default)</strong></td>
<td><code>s(x)</code></td>
<td>Flexible, general-purpose spline that does not require knot placement.</td>
<td>Default in <code><a href="https://rdrr.io/pkg/mgcv/man/s.html">mgcv::s()</a></code>; works well in most situations.</td>
</tr>
<tr class="even">
<td><strong>Cubic regression spline</strong></td>
<td><code>s(x, bs = "cr")</code></td>
<td>Standard cubic spline with specified knots.</td>
<td>Good when you want explicit control over knots or smoothness.</td>
</tr>
<tr class="odd">
<td><strong>Cyclic spline</strong></td>
<td><code>s(x, bs = "cc")</code></td>
<td>Ensures smooth connection at boundaries for circular predictors.</td>
<td>Ideal for seasonal or periodic variables (e.g., day-of-year).</td>
</tr>
<tr class="even">
<td><strong>P-spline</strong></td>
<td><code>s(x, bs = "ps")</code></td>
<td>Penalized B-spline allowing control over wiggliness via penalties.</td>
<td>Useful for evenly spaced predictors; can handle large datasets efficiently.</td>
</tr>
<tr class="odd">
<td><strong>Thin plate regression spline with shrinkage</strong></td>
<td><code>s(x, bs = "ts")</code></td>
<td>Adds extra penalization to allow smooth term to shrink to zero if not important.</td>
<td>Useful for model selection or when some smooth terms may be irrelevant.</td>
</tr>
<tr class="even">
<td><strong>Tensor product smooths</strong></td>
<td><code>te(x1, x2)</code></td>
<td>Combines multiple continuous predictors, allowing interactions on different scales.</td>
<td>Use for multidimensional ecological responses (e.g., temperature × flow).</td>
</tr>
</tbody>
</table></div>
</div>
<div id="penalty-strength" class="section level3" number="18.2.2">
<h3>
<span class="header-section-number">18.2.2</span> Penalty strength<a class="anchor" aria-label="anchor" href="#penalty-strength"><i class="fas fa-link"></i></a>
</h3>
<p>In a GAM, smooth terms are flexible functions whose degree of curvature (wiggliness) must be estimated from the data. In the <code>mgcv</code> package, this is done automatically by selecting a smoothing parameter that balances goodness of fit against model complexity.</p>
<p>By default, mgcv uses generalized cross-validation (GCV) to determine this smoothing parameter. <strong>In other words, GCV decides the strength of the penalty applied to the smooth term</strong>: a stronger penalty produces a smoother, less wiggly curve, while a weaker penalty allows more flexibility to follow data fluctuations. Conceptually, GCV asks: <em>How well would this model predict new data if we slightly penalize excessive curvature?</em> A smoother that fits the data too closely (overfitting) is penalized, while a smoother that is too rigid (underfitting) fails to capture important structure. The chosen smoothness minimizes the GCV score, yielding a curve that is flexible enough to capture real patterns but smooth enough to generalize beyond the observed data.</p>
<p>However, there are other options for the penalty selection method, which can be specified via the <code>method</code> argument in <code><a href="https://rdrr.io/pkg/mgcv/man/gam.html">mgcv::gam()</a></code>:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="25%">
<col width="25%">
<col width="49%">
</colgroup>
<thead><tr class="header">
<th>Penalty Selection Method</th>
<th>How to Specify</th>
<th>Notes / Typical Use</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>GCV / GACV</strong></td>
<td>
<code>method = "GCV.Cp"</code> (or default)</td>
<td>Balances fit vs. wiggliness; default in many examples.</td>
</tr>
<tr class="even">
<td><strong>REML</strong></td>
<td><code>method = "REML"</code></td>
<td>Preferred for stable inference; treats smoothness as a variance component.</td>
</tr>
<tr class="odd">
<td><strong>ML</strong></td>
<td><code>method = "ML"</code></td>
<td>Useful for comparing nested models using likelihood-based criteria.</td>
</tr>
<tr class="even">
<td><strong>UBRE / P-UBRE</strong></td>
<td><code>method = "UBRE"</code></td>
<td>Based on unbiased risk estimate; mainly for Gaussian models.</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="laboratory-11" class="section level2" number="18.3">
<h2>
<span class="header-section-number">18.3</span> Laboratory<a class="anchor" aria-label="anchor" href="#laboratory-11"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="generalized-linear-mixed-effect-model.html"><span class="header-section-number">17</span> Generalized Linear Mixed Effect Model</a></div>
<div class="next"><a href="unconstrained-ordination.html"><span class="header-section-number">19</span> Unconstrained Ordination</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#generalized-additive-model"><span class="header-section-number">18</span> Generalized Additive Model</a></li>
<li>
<a class="nav-link" href="#seasonal-data"><span class="header-section-number">18.1</span> Seasonal Data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#water-temperature-example"><span class="header-section-number">18.1.1</span> Water temperature example</a></li>
<li><a class="nav-link" href="#smooth-function"><span class="header-section-number">18.1.2</span> Smooth function</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#estimating-smoothness"><span class="header-section-number">18.2</span> Estimating Smoothness</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#choice-of-smooth-function"><span class="header-section-number">18.2.1</span> Choice of smooth function</a></li>
<li><a class="nav-link" href="#penalty-strength"><span class="header-section-number">18.2.2</span> Penalty strength</a></li>
</ul>
</li>
<li><a class="nav-link" href="#laboratory-11"><span class="header-section-number">18.3</span> Laboratory</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/aterui/biostats/blob/master/chapters/adv-02-gam.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/aterui/biostats/edit/master/chapters/adv-02-gam.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BIOSTATS</strong>" was written by Akira Terui. It was last built on 2025-12-21.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
