<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 7 Linear Model | BIOSTATS</title>
<meta name="author" content="Akira Terui">
<meta name="description" content="We have extensively covered three important statistical analyses: the t-test, ANOVA, and regression analysis. While these methods may seem distinct, they all fall under the umbrella of the Linear...">
<meta name="generator" content="bookdown 0.29 with bs4_book()">
<meta property="og:title" content="Chapter 7 Linear Model | BIOSTATS">
<meta property="og:type" content="book">
<meta property="og:url" content="https://bookdown.org/janedoe/bookdown-demo/linear-model.html">
<meta property="og:description" content="We have extensively covered three important statistical analyses: the t-test, ANOVA, and regression analysis. While these methods may seem distinct, they all fall under the umbrella of the Linear...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 7 Linear Model | BIOSTATS">
<meta name="twitter:description" content="We have extensively covered three important statistical analyses: the t-test, ANOVA, and regression analysis. While these methods may seem distinct, they all fall under the umbrella of the Linear...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BIOSTATS</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Introduction</a></li>
<li><a class="" href="descriptive-statistics.html"><span class="header-section-number">1</span> Descriptive Statistics</a></li>
<li><a class="" href="sampling.html"><span class="header-section-number">2</span> Sampling</a></li>
<li><a class="" href="probabilistic-view.html"><span class="header-section-number">3</span> Probabilistic View</a></li>
<li><a class="" href="two-group-comparison.html"><span class="header-section-number">4</span> Two-Group Comparison</a></li>
<li><a class="" href="multiple-group-comparison.html"><span class="header-section-number">5</span> Multiple-Group Comparison</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">6</span> Regression</a></li>
<li><a class="active" href="linear-model.html"><span class="header-section-number">7</span> Linear Model</a></li>
<li><a class="" href="generalized-linear-model.html"><span class="header-section-number">8</span> Generalized Linear Model</a></li>
<li><a class="" href="likelihood.html"><span class="header-section-number">9</span> Likelihood</a></li>
<li><a class="" href="model-comparison.html"><span class="header-section-number">10</span> Model Comparison</a></li>
<li><a class="" href="appendix-project.html">Appendix: Project</a></li>
<li><a class="" href="appendix-git-github.html">Appendix: Git &amp; GitHub</a></li>
<li><a class="" href="appendix-data-structure.html">Appendix: Data Structure</a></li>
<li><a class="" href="appendix-tidyverse.html">Appendix: Tidyverse</a></li>
<li><a class="" href="appendix-base-plot.html">Appendix: Base Plot</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/aterui/biostats">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="linear-model" class="section level1" number="7">
<h1>
<span class="header-section-number">7</span> Linear Model<a class="anchor" aria-label="anchor" href="#linear-model"><i class="fas fa-link"></i></a>
</h1>
<p>We have extensively covered three important statistical analyses: the t-test, ANOVA, and regression analysis. While these methods may seem distinct, they all fall under the umbrella of the Linear Model framework<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Some textbooks refer to this framework as “General Linear Model.” However, to distinguish from Generalized Linear Model, I call this “Linear Model.”&lt;/p&gt;"><sup>4</sup></a>.</p>
<p>The Linear Model encompasses models that depict the connection between a response variable and one or more explanatory variables. It assumes that the error term follows a normal distribution. In this chapter, I will elucidate this framework and illustrate its relationship to the t-test, ANOVA, and regression analysis.</p>
<div id="the-frame" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> The Frame<a class="anchor" aria-label="anchor" href="#the-frame"><i class="fas fa-link"></i></a>
</h2>
<p>The apparent distinctiveness between the t-test, ANOVA, and regression analysis arises because they are applied to different types of data:</p>
<ul>
<li>t-test: comparing differences between two groups.</li>
<li>ANOVA: examining differences among more than two groups.</li>
<li>Regression: exploring the relationship between a response variable and one or more explanatory variables.</li>
</ul>
<p>Despite these differences, these analyses can be unified under a single formula. As discussed in the regression formula in Chapter <a href="regression.html#regression">6</a>, we have:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;= \alpha + \beta_1 x_{1,i} + \varepsilon_i\\
\varepsilon_i &amp;\sim \text{Normal}(0, \sigma^2)
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> represents the response variable (such as fish body length or plant height), <span class="math inline">\(x_{1,i}\)</span> denotes the continuous explanatory variable, <span class="math inline">\(\alpha\)</span> represents the intercept, and <span class="math inline">\(\beta_1\)</span> corresponds to the slope. The equivalent model can be expressed differently as follows:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \text{Normal}(\mu_i, \sigma^2)\\
\mu_i &amp;= \alpha + \beta_1 x_{1,i}
\end{aligned}
\]</span></p>
<p>This structure provides insight into the relationship between the t-test, ANOVA, and regression analysis. The fundamental purpose of regression analysis is to model how the mean <span class="math inline">\(\mu_i\)</span> changes with increasing or decreasing values of <span class="math inline">\(x_{1,i}\)</span>. Thus, the t-test, ANOVA, and regression all analyze the mean – the expected value of a Normal distribution. The primary distinction between the t-test, ANOVA, and regression lies in the nature of the explanatory variable, which can be either continuous or categorical (group).</p>
<div id="two-group-case" class="section level3" number="7.1.1">
<h3>
<span class="header-section-number">7.1.1</span> Two-Group Case<a class="anchor" aria-label="anchor" href="#two-group-case"><i class="fas fa-link"></i></a>
</h3>
<p>To establish a connection among these approaches, one can employ “dummy indicator” variables to represent group variables. In the case of the t-test, where a categorical variable consists of two groups, typically denoted as <code>a</code> and <code>b</code> (although they can be represented by numbers as well), one can convert these categories into numerical values. For instance, assigning <code>a</code> to 0 and <code>b</code> to 1 enables the following conversion:</p>
<p><span class="math display">\[
\pmb{x'}_2 =
\begin{pmatrix}
   a\\
   a\\
   b\\
   \vdots\\
   b\end{pmatrix}
\rightarrow
\pmb{x}_2 =
\begin{pmatrix}
0\\
0\\
1\\
\vdots\\
1
\end{pmatrix}
\]</span></p>
<p>The model can be written as:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \text{Normal}(\mu_i, \sigma^2)\\
\mu_i &amp;= \alpha + \beta_2 x_{2,i}
\end{aligned}
\]</span></p>
<p>When incorporating this variable into the model, some interesting outcomes arise. Since <span class="math inline">\(x_{2,i} = 0\)</span> when an observation belongs to group <code>a</code>, the mean of group <code>a</code> (<span class="math inline">\(\mu_i = \mu_a\)</span>) is determined as <span class="math inline">\(\mu_a = \alpha + \beta \times 0 = \alpha\)</span>. Consequently, the intercept represents the mean value of the first group. On the other hand, if an observation is from group <code>b</code>, the mean of group <code>b</code> (<span class="math inline">\(\mu_i = \mu_b\)</span>) is given by <span class="math inline">\(\mu_b = \alpha + \beta \times 1 = \alpha + \beta\)</span>. It’s important to recall that <span class="math inline">\(\mu_a = \alpha\)</span>. By substituting <span class="math inline">\(\alpha\)</span> with <span class="math inline">\(\mu_a\)</span>, the equation <span class="math inline">\(\beta = \mu_b - \mu_a\)</span> is obtained, indicating that the slope represents the difference between the means of the two groups – the key statistic in the t-test.</p>
<p>Let me confirm this using the dataset in Chapter <a href="two-group-comparison.html#two-group-comparison">4</a> (fish body length in two lakes):</p>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="va">df_fl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data_raw/data_fish_length.csv"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_fl</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 100 × 3
##    lake  length unit 
##    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;
##  1 a       10.8 cm   
##  2 a       13.6 cm   
##  3 a       10.1 cm   
##  4 a       18.6 cm   
##  5 a       14.2 cm   
##  6 a       10.1 cm   
##  7 a       14.7 cm   
##  8 a       15.6 cm   
##  9 a       15   cm   
## 10 a       11.9 cm   
## # ℹ 90 more rows</code></pre>
<p>In the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function, when you provide a “categorical” variable in character or factor form, it is automatically converted to a binary (0/1) variable internally. This means that you can include this variable in the formula as if you were conducting a standard regression analysis. The <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function takes care of this conversion process, allowing you to seamlessly incorporate categorical variables into the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function.</p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># group means</span></span>
<span><span class="va">v_mu</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">lake</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># mu_a: should be identical to intercept</span></span>
<span><span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 13.35</code></pre>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># mu_b - mu_a: should be identical to slope</span></span>
<span><span class="va">v_mu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 2.056</code></pre>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># in lm(), letters are automatically converted to 0/1 binary variable.</span></span>
<span><span class="co"># alphabetically ordered (in this case, a = 0, b = 1)</span></span>
<span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">lake</span>,</span>
<span>        data <span class="op">=</span> <span class="va">df_fl</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = length ~ lake, data = df_fl)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.150 -2.156  0.022  2.008  7.994 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  13.3500     0.4477  29.819   &lt;2e-16 ***
## lakeb         2.0560     0.6331   3.247   0.0016 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.166 on 98 degrees of freedom
## Multiple R-squared:  0.09715,    Adjusted R-squared:  0.08794 
## F-statistic: 10.55 on 1 and 98 DF,  p-value: 0.001596</code></pre>
<p>The estimated coefficient of Lake <code>b</code> (<code>lakeb</code>) is identical to the difference between group means. We can compare other statistics (<code>t value</code> and <code>Pr(&gt;|t|</code>) with the output from <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> as well:</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lake_a</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">lake</span> <span class="op">==</span> <span class="st">"a"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lake_b</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">lake</span> <span class="op">==</span> <span class="st">"b"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">lake_b</span>, y <span class="op">=</span> <span class="va">lake_a</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  lake_b and lake_a
## t = 3.2473, df = 95.846, p-value = 0.001606
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.7992071 3.3127929
## sample estimates:
## mean of x mean of y 
##    15.406    13.350</code></pre>
<p>The t-statistic and p-value match the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> output.</p>
</div>
<div id="multiple-group-case" class="section level3" number="7.1.2">
<h3>
<span class="header-section-number">7.1.2</span> Multiple-Group Case<a class="anchor" aria-label="anchor" href="#multiple-group-case"><i class="fas fa-link"></i></a>
</h3>
<p>The same argument applies to ANOVA. In ANOVA, we deal with more than two groups in the explanatory variable. To handle this, we can convert the group variable into multiple dummy variables. For instance, if we have a variable <span class="math inline">\(\pmb{x'}_2 = \{a, b, c\}\)</span>, we can convert it to <span class="math inline">\(x_2 = \{0, 1, 0\}\)</span> (where <span class="math inline">\(b \rightarrow 1\)</span> and the others are <span class="math inline">\(0\)</span>) and <span class="math inline">\(\pmb{x}_3 = \{0, 0, 1\}\)</span> (where <span class="math inline">\(c \rightarrow 1\)</span> and the others are <span class="math inline">\(0\)</span>). Thus, the model formula would be:</p>
<p><span class="math display">\[
\begin{aligned}
y_i &amp;\sim \text{Normal}(\mu_i, \sigma^2)\\
\mu_i &amp;= \alpha + \beta_{2} x_{2,i}  + \beta_{3} x_{3,i}
\end{aligned}
\]</span></p>
<p>If you substitute these dummy variables, then:</p>
<p><span class="math display">\[
\begin{aligned}
\mu_a &amp;= \alpha + \beta_2 \times 0 + \beta_3 \times 0 = \alpha &amp;&amp;\text{both}~x_{2,i}~\text{and}~x_{3,i}~\text{are zero}\\
\mu_b &amp;= \alpha + \beta_2 \times 1 + \beta_3 \times 0 = \alpha + \beta_2 &amp;&amp;x_{2,i} = 1~\text{but}~x_{3,i}=0\\
\mu_c &amp;= \alpha + \beta_2 \times 0 + \beta_3 \times 1 = \alpha + \beta_3 &amp;&amp;x_{2,i} = 0~\text{but}~x_{3,i}=1\\
\end{aligned}
\]</span></p>
<p>Therefore, the group <code>a</code> serves as the reference, and the <span class="math inline">\(\beta\)</span>s represent the deviations from the reference group. Now, let me attempt the ANOVA dataset provided in Chapter <a href="multiple-group-comparison.html#multiple-group-comparison">5</a>:</p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_anova</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data_raw/data_fish_length_anova.csv"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_anova</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 150 × 3
##    lake  length unit 
##    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;
##  1 a       10.8 cm   
##  2 a       13.6 cm   
##  3 a       10.1 cm   
##  4 a       18.6 cm   
##  5 a       14.2 cm   
##  6 a       10.1 cm   
##  7 a       14.7 cm   
##  8 a       15.6 cm   
##  9 a       15   cm   
## 10 a       11.9 cm   
## # ℹ 140 more rows</code></pre>
<p>Again, the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function converts the categorical variable to the dummy variables internally. Compare the mean and differences with the estimated parameters:</p>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># group means</span></span>
<span><span class="va">v_mu</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">lake</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="co"># mu_a: should be identical to intercept</span></span>
<span>        <span class="va">v_mu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="co"># mu_b - mu_a: should be identical to the slope for lakeb</span></span>
<span>        <span class="va">v_mu</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="co"># mu_c - mu_a: should be identical to the slope for lakec</span></span></code></pre></div>
<pre><code>## [1] 13.350  2.056     NA</code></pre>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># lm() output</span></span>
<span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">lake</span>,</span>
<span>        data <span class="op">=</span> <span class="va">df_anova</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = length ~ lake, data = df_anova)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.150 -1.862 -0.136  1.846  7.994 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  13.3500     0.4469  29.875  &lt; 2e-16 ***
## lakeb         2.0560     0.6319   3.253  0.00141 ** 
## lakec         1.1160     0.6319   1.766  0.07948 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.16 on 147 degrees of freedom
## Multiple R-squared:  0.06732,    Adjusted R-squared:  0.05463 
## F-statistic: 5.305 on 2 and 147 DF,  p-value: 0.005961</code></pre>
<p>Also, there is a report for F-statistic (<code>5.305</code>) and p-value (<code>0.005961</code>). Compare them with the <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code> output:</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m_aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/aov.html">aov</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">lake</span>,</span>
<span>             data <span class="op">=</span> <span class="va">df_anova</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_aov</span><span class="op">)</span></span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## lake          2  105.9   52.97   5.305 0.00596 **
## Residuals   147 1467.6    9.98                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The results are identical.</p>
</div>
<div id="the-common-structure" class="section level3" number="7.1.3">
<h3>
<span class="header-section-number">7.1.3</span> The Common Structure<a class="anchor" aria-label="anchor" href="#the-common-structure"><i class="fas fa-link"></i></a>
</h3>
<p>The above examples show that the t-test, ANOVA, and regression has the same model structure:</p>
<p><span class="math display">\[
y_i = \text{(deterministic component)} + \text{(stochastic component)}
\]</span> In the framework of the Linear Model, the deterministic component is expressed as <span class="math inline">\(\alpha + \sum_k \beta_k x_{k,i}\)</span> and the stochastic component (random error) is expressed as a Normal distribution. This structure makes several assumptions. Here are the main assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity: The relationship between the explanatory variables and the response variable is linear. This means that the effect of each explanatory variable on the response variable is additive and constant.</p></li>
<li><p>Independence: The observations are independent of each other. This assumption implies that the values of the response variable for one observation do not influence the values for other observations.</p></li>
<li><p>Homoscedasticity: The variance of the response variable is constant across all levels of the explanatory variables. In other words, the spread or dispersion of the response variable should be the same for all values of the explanatory variables.</p></li>
<li><p>Normality: The error term follows a normal distribution at each level of the explanatory variables. This assumption is important because many statistical tests and estimators used in the linear model are based on the assumption of normality.</p></li>
<li><p>No multicollinearity: The explanatory variables are not highly correlated with each other. Multicollinearity can lead to problems in estimating the coefficients accurately and can make interpretation difficult.</p></li>
</ol>
<p>Violations of these assumptions can affect the validity and reliability of the results obtained from the Linear Model.</p>
</div>
</div>
<div id="combine-multiple-types-of-variables" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Combine Multiple Types of Variables<a class="anchor" aria-label="anchor" href="#combine-multiple-types-of-variables"><i class="fas fa-link"></i></a>
</h2>
<div id="iris-example" class="section level3" number="7.2.1">
<h3>
<span class="header-section-number">7.2.1</span> <code>iris</code> Example<a class="anchor" aria-label="anchor" href="#iris-example"><i class="fas fa-link"></i></a>
</h3>
<p>The previous section clarified that the t-test, ANOVA, and regression have a common model structure; therefore, categorical and continuous variables can be included in the same model. Here, let me use the <code>iris</code> data (available in R by default) to show an example. This data set comprises continuous (Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) and categorical variables (Species):</p>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># convert the data format to tibble</span></span>
<span><span class="va">iris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">iris</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">iris</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 150 × 5
##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
##           &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  
##  1          5.1         3.5          1.4         0.2 setosa 
##  2          4.9         3            1.4         0.2 setosa 
##  3          4.7         3.2          1.3         0.2 setosa 
##  4          4.6         3.1          1.5         0.2 setosa 
##  5          5           3.6          1.4         0.2 setosa 
##  6          5.4         3.9          1.7         0.4 setosa 
##  7          4.6         3.4          1.4         0.3 setosa 
##  8          5           3.4          1.5         0.2 setosa 
##  9          4.4         2.9          1.4         0.2 setosa 
## 10          4.9         3.1          1.5         0.1 setosa 
## # ℹ 140 more rows</code></pre>
<div class="sourceCode" id="cb200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">iris</span>, <span class="va">Species</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 3 × 1
##   Species   
##   &lt;fct&gt;     
## 1 setosa    
## 2 versicolor
## 3 virginica</code></pre>
<p>Here, let me model <code>Petal.Length</code> as a function of <code>Petal.Width</code> and <code>Species</code>:</p>
<div class="sourceCode" id="cb202"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># develop iris model</span></span>
<span><span class="va">m_iris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Petal.Length</span> <span class="op">~</span> <span class="va">Petal.Width</span> <span class="op">+</span> <span class="va">Species</span>,</span>
<span>             data <span class="op">=</span> <span class="va">iris</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_iris</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Petal.Length ~ Petal.Width + Species, data = iris)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.02977 -0.22241 -0.01514  0.18180  1.17449 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        1.21140    0.06524  18.568  &lt; 2e-16 ***
## Petal.Width        1.01871    0.15224   6.691 4.41e-10 ***
## Speciesversicolor  1.69779    0.18095   9.383  &lt; 2e-16 ***
## Speciesvirginica   2.27669    0.28132   8.093 2.08e-13 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3777 on 146 degrees of freedom
## Multiple R-squared:  0.9551, Adjusted R-squared:  0.9542 
## F-statistic:  1036 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Please note that the model output does not include <code>setosa</code> because it was used as the reference group (<code>(Intercept)</code>).</p>
<p>If you want to obtain predicted values, you can use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function. To make predictions, you need to provide a new data frame containing the values of explanatory variables for the prediction.</p>
<div class="sourceCode" id="cb204"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># create a data frame for prediction</span></span>
<span><span class="co"># variable names must be identical to the original dataframe for analysis</span></span>
<span><span class="va">n_rep</span> <span class="op">&lt;-</span> <span class="fl">100</span></span>
<span><span class="va">df_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>Petal.Width <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">iris</span><span class="op">$</span><span class="va">Petal.Width</span><span class="op">)</span>,</span>
<span>                                        <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">iris</span><span class="op">$</span><span class="va">Petal.Width</span><span class="op">)</span>,</span>
<span>                                        length <span class="op">=</span> <span class="va">n_rep</span><span class="op">)</span>,</span>
<span>                                    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct</a></span><span class="op">(</span><span class="va">iris</span><span class="op">$</span><span class="va">Species</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                  Species <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">iris</span><span class="op">$</span><span class="va">Species</span><span class="op">)</span>,</span>
<span>                                each <span class="op">=</span> <span class="va">n_rep</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># make prediction based on supplied values of explanatory variables</span></span>
<span><span class="va">y_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_iris</span>,</span>
<span>                  newdata <span class="op">=</span> <span class="va">df_pred</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_pred</span> <span class="op">&lt;-</span> <span class="va">df_pred</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>y_pred <span class="op">=</span> <span class="va">y_pred</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_pred</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 300 × 3
##    Petal.Width Species y_pred
##          &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;
##  1       0.1   setosa    1.31
##  2       0.124 setosa    1.34
##  3       0.148 setosa    1.36
##  4       0.173 setosa    1.39
##  5       0.197 setosa    1.41
##  6       0.221 setosa    1.44
##  7       0.245 setosa    1.46
##  8       0.270 setosa    1.49
##  9       0.294 setosa    1.51
## 10       0.318 setosa    1.54
## # ℹ 290 more rows</code></pre>
<p>By plotting the predicted values against the observed data points, we can visually evaluate the accuracy of the model and assess its goodness of fit.</p>
<div class="sourceCode" id="cb206"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">iris</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Petal.Width</span>,</span>
<span>             y <span class="op">=</span> <span class="va">Petal.Length</span>,</span>
<span>             color <span class="op">=</span> <span class="va">Species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_pred</span>,</span>
<span>            <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">y_pred</span><span class="op">)</span><span class="op">)</span> <span class="co"># redefine y values for lines; x and color are inherited from ggplot()</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:iris-plot"></span>
<img src="biostats_files/figure-html/iris-plot-1.png" alt="Example of model fitting to iris data. Points are observations, and lines are model predictions." width="672"><p class="caption">
Figure 7.1: Example of model fitting to iris data. Points are observations, and lines are model predictions.
</p>
</div>
</div>
<div id="variable-types" class="section level3" number="7.2.2">
<h3>
<span class="header-section-number">7.2.2</span> Variable Types<a class="anchor" aria-label="anchor" href="#variable-types"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li><p><strong>Categorical Variables</strong>: Qualitative or discrete characteristics that fall into specific categories or groups. They do not have a numerical value or order associated with them. Examples: gender (male/female), marital status (single/married/divorced), and color (red/green/blue).</p></li>
<li><p><strong>Ordinal Variables</strong>: Categories or levels with a natural order or ranking. Examples: survey ratings (e.g., Likert scale), education levels (e.g., high school, bachelor’s, master’s), or socioeconomic status (e.g., low, medium, high).</p></li>
<li><p><strong>Interval Variables</strong>: Numerical values representing a continuous scale where the intervals between the values are meaningful and consistent. Unlike ordinal variables, interval variables have equally spaced intervals between adjacent values, allowing for meaningful arithmetic operations like addition and subtraction. However, interval variables do not contain a natural zero point; zero is arbitrary and merely a reference point. Examples: temperature</p></li>
<li><p><strong>Ratio Variables</strong>: Numerical variable that shares the characteristics of interval variables but also has a meaningful and absolute zero point. Thus, this type of variables has the complete absence of the measured attribute/quantity. Examples: height (in centimeters), weight (in kilograms), time (in seconds), distance (in meters), and income (in dollars).</p></li>
</ol>
<p>We cannot carry out meaningful arithmetic operations on categorical and ordinal variables; therefore, we should treat these variables as as “character” or “factors” in R. This is because R recognizes that the intervals between different groups or levels of these variables are not meaningful in a numerical sense.</p>
<p>In contrast, interval and ratio variables should be considered “numerical” variables in R. These variables possess a meaningful numerical scale with equal intervals, and in the case of ratio variables, a true zero point.</p>
</div>
</div>
<div id="laboratory-6" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> Laboratory<a class="anchor" aria-label="anchor" href="#laboratory-6"><i class="fas fa-link"></i></a>
</h2>
<div id="normality-assumption" class="section level3" number="7.3.1">
<h3>
<span class="header-section-number">7.3.1</span> Normality Assumption<a class="anchor" aria-label="anchor" href="#normality-assumption"><i class="fas fa-link"></i></a>
</h3>
<p>The Linear Model framework assumes normality. To verify the validity of the normality assumption, we typically employ the Shapiro-Wilk test (<code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code> in R). Discuss whether the test should be applied to (1) the response variable or (2) model residuals. Then apply the Shapiro-Wilk test to the model <code>m_iris</code>. Type <code><a href="https://rdrr.io/r/stats/shapiro.test.html">?shapiro.test</a></code> in the R console to learn more about its usage.</p>
</div>
<div id="model-interpretation" class="section level3" number="7.3.2">
<h3>
<span class="header-section-number">7.3.2</span> Model Interpretation<a class="anchor" aria-label="anchor" href="#model-interpretation"><i class="fas fa-link"></i></a>
</h3>
<p>The model depicted in Figure <a href="linear-model.html#fig:iris-plot">7.1</a> can be interpreted as follows: “each species has a distinct intercept value.” Extract the intercept values for each species from the <code>m_iris</code> object.</p>
</div>
<div id="alternative-model" class="section level3" number="7.3.3">
<h3>
<span class="header-section-number">7.3.3</span> Alternative Model<a class="anchor" aria-label="anchor" href="#alternative-model"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s explore an alternative model that does not consider the species’ identity. How would this modification affect the results? Develop a model excluding the <code>Species</code> variable and create a new figure resembling Figure <a href="linear-model.html#fig:iris-plot">7.1</a>, but with a single regression line.</p>

</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="regression.html"><span class="header-section-number">6</span> Regression</a></div>
<div class="next"><a href="generalized-linear-model.html"><span class="header-section-number">8</span> Generalized Linear Model</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#linear-model"><span class="header-section-number">7</span> Linear Model</a></li>
<li>
<a class="nav-link" href="#the-frame"><span class="header-section-number">7.1</span> The Frame</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#two-group-case"><span class="header-section-number">7.1.1</span> Two-Group Case</a></li>
<li><a class="nav-link" href="#multiple-group-case"><span class="header-section-number">7.1.2</span> Multiple-Group Case</a></li>
<li><a class="nav-link" href="#the-common-structure"><span class="header-section-number">7.1.3</span> The Common Structure</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#combine-multiple-types-of-variables"><span class="header-section-number">7.2</span> Combine Multiple Types of Variables</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#iris-example"><span class="header-section-number">7.2.1</span> iris Example</a></li>
<li><a class="nav-link" href="#variable-types"><span class="header-section-number">7.2.2</span> Variable Types</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#laboratory-6"><span class="header-section-number">7.3</span> Laboratory</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#normality-assumption"><span class="header-section-number">7.3.1</span> Normality Assumption</a></li>
<li><a class="nav-link" href="#model-interpretation"><span class="header-section-number">7.3.2</span> Model Interpretation</a></li>
<li><a class="nav-link" href="#alternative-model"><span class="header-section-number">7.3.3</span> Alternative Model</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/aterui/biostats/blob/master/chapters/07-lm.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/aterui/biostats/edit/master/chapters/07-lm.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BIOSTATS</strong>" was written by Akira Terui. It was last built on 2023-07-24.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
