<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 22 Time-Series Analysis | BIOSTATS</title>
<meta name="author" content="Akira Terui">
<meta name="description" content="Time-Series Analysis is one of the most challenging topics in statistics because it violates a fundamental assumption: the independence of data points. Nevertheless, this type of data is common in...">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="Chapter 22 Time-Series Analysis | BIOSTATS">
<meta property="og:type" content="book">
<meta property="og:description" content="Time-Series Analysis is one of the most challenging topics in statistics because it violates a fundamental assumption: the independence of data points. Nevertheless, this type of data is common in...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 22 Time-Series Analysis | BIOSTATS">
<meta name="twitter:description" content="Time-Series Analysis is one of the most challenging topics in statistics because it violates a fundamental assumption: the independence of data points. Nevertheless, this type of data is common in...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-QZSNHVQQNV"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-QZSNHVQQNV');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BIOSTATS</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Introduction</a></li>
<li class="book-part">Getting Started</li>
<li><a class="" href="what-is-r-and-r-studio.html"><span class="header-section-number">1</span> What is R and R studio?</a></li>
<li><a class="" href="installing-r-and-rstudio.html"><span class="header-section-number">2</span> Installing R and RStudio</a></li>
<li><a class="" href="r-project.html"><span class="header-section-number">3</span> R Project</a></li>
<li class="book-part">R Basics</li>
<li><a class="" href="data-structure.html"><span class="header-section-number">4</span> Data Structure</a></li>
<li><a class="" href="data-manipulation.html"><span class="header-section-number">5</span> Data Manipulation</a></li>
<li><a class="" href="visualization.html"><span class="header-section-number">6</span> Visualization</a></li>
<li class="book-part">Basic Statistics</li>
<li><a class="" href="descriptive-statistics.html"><span class="header-section-number">7</span> Descriptive Statistics</a></li>
<li><a class="" href="sampling.html"><span class="header-section-number">8</span> Sampling</a></li>
<li><a class="" href="probabilistic-view.html"><span class="header-section-number">9</span> Probabilistic View</a></li>
<li><a class="" href="two-group-comparison.html"><span class="header-section-number">10</span> Two-Group Comparison</a></li>
<li><a class="" href="multiple-group-comparison.html"><span class="header-section-number">11</span> Multiple-Group Comparison</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">12</span> Regression</a></li>
<li><a class="" href="linear-model.html"><span class="header-section-number">13</span> Linear Model</a></li>
<li><a class="" href="generalized-linear-model.html"><span class="header-section-number">14</span> Generalized Linear Model</a></li>
<li><a class="" href="likelihood.html"><span class="header-section-number">15</span> Likelihood</a></li>
<li><a class="" href="model-comparison.html"><span class="header-section-number">16</span> Model Comparison</a></li>
<li class="book-part">Applied Statistics</li>
<li><a class="" href="generalized-linear-mixed-effect-model.html"><span class="header-section-number">17</span> Generalized Linear Mixed Effect Model</a></li>
<li><a class="" href="generalized-additive-model.html"><span class="header-section-number">18</span> Generalized Additive Model</a></li>
<li><a class="" href="unconstrained-ordination.html"><span class="header-section-number">19</span> Unconstrained Ordination</a></li>
<li><a class="" href="constrained-ordination.html"><span class="header-section-number">20</span> Constrained Ordination</a></li>
<li><a class="" href="structural-equation-modeling.html"><span class="header-section-number">21</span> Structural Equation Modeling</a></li>
<li><a class="active" href="time-series-analysis.html"><span class="header-section-number">22</span> Time-Series Analysis</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="basic-terminology.html">Basic Terminology</a></li>
<li><a class="" href="git-github.html">Git &amp; GitHub</a></li>
<li><a class="" href="base-plot.html">Base Plot</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/aterui/biostats">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="time-series-analysis" class="section level1" number="22">
<h1>
<span class="header-section-number">22</span> Time-Series Analysis<a class="anchor" aria-label="anchor" href="#time-series-analysis"><i class="fas fa-link"></i></a>
</h1>
<p>Time-Series Analysis is one of the most challenging topics in statistics because it violates a fundamental assumption: the independence of data points. Nevertheless, this type of data is common in biology and is often analyzed incorrectly. In this section, we will explore common pitfalls in time-series analysis and review statistical models that can account for temporal dependence.</p>
<p>Learning Objectives:</p>
<ul>
<li><p>Understand the challenges inherent in time-series analysis.</p></li>
<li><p>Learn basic modeling approaches for time-series data.</p></li>
<li><p>Learn how to incorporate external predictors into time-series models.</p></li>
</ul>
<div class="sourceCode" id="cb569"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>,</span>
<span>               <span class="va">forecast</span>,</span>
<span>               <span class="va">lterdatasampler</span>,</span>
<span>               <span class="va">daymetr</span>,</span>
<span>               <span class="va">glarma</span><span class="op">)</span></span></code></pre></div>
<div id="pitfall-of-time-series" class="section level2" number="22.1">
<h2>
<span class="header-section-number">22.1</span> Pitfall of Time-Series<a class="anchor" aria-label="anchor" href="#pitfall-of-time-series"><i class="fas fa-link"></i></a>
</h2>
<div id="time-series-anormalies" class="section level3" number="22.1.1">
<h3>
<span class="header-section-number">22.1.1</span> Time-series anormalies<a class="anchor" aria-label="anchor" href="#time-series-anormalies"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s explore a simple time series dataset, showing air-quality anomalies measured over 100 years.</p>
<div class="sourceCode" id="cb570"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">url</span> <span class="op">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/aterui/biostats/master/data_raw/data_ts_anormaly.csv"</span></span>
<span><span class="op">(</span><span class="va">df_ts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">url</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 100 × 2
##    anormaly  year
##       &lt;dbl&gt; &lt;dbl&gt;
##  1    0      1926
##  2   -0.560  1927
##  3   -0.791  1928
##  4    0.768  1929
##  5    0.839  1930
##  6    0.968  1931
##  7    2.68   1932
##  8    3.14   1933
##  9    1.88   1934
## 10    1.19   1935
## # ℹ 90 more rows</code></pre>
<p>The plot of this dataset shows that air-quality anomalies tend to increase over time.</p>
<div class="sourceCode" id="cb572"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Plot time-series anomalies</span></span>
<span><span class="va">df_ts</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>,          <span class="co"># Map 'year' to the x-axis</span></span>
<span>             y <span class="op">=</span> <span class="va">anormaly</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>  <span class="co"># Map 'anormaly' to the y-axis</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>                  <span class="co"># Add a line connecting the points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>                 <span class="co"># Add points at each observation</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>                   <span class="co"># Use a clean black-and-white theme</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Year"</span>,                     <span class="co"># Label x-axis</span></span>
<span>    y <span class="op">=</span> <span class="st">"Anomaly"</span>                   <span class="co"># Label y-axis</span></span>
<span>  <span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-random-walk-plot"></span>
<img src="biostats_files/figure-html/adv-06-random-walk-plot-1.png" alt="Time-series of annual anomalies. Points represent observed values for each year, and lines connect consecutive observations to highlight temporal trends." width="672"><p class="caption">
Figure 22.1: Time-series of annual anomalies. Points represent observed values for each year, and lines connect consecutive observations to highlight temporal trends.
</p>
</div>
<p>Providing statistical evidence appears straightforward — we can simply regress anomalies on time.</p>
<div class="sourceCode" id="cb573"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Fit a simple linear model: anomaly as a function of year</span></span>
<span><span class="va">m_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">anormaly</span> <span class="op">~</span> <span class="va">year</span>, data <span class="op">=</span> <span class="va">df_ts</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Show the model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_lm</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = anormaly ~ year, data = df_ts)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.0830 -1.1333 -0.1559  1.2911  5.6330 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -90.770684  12.715802  -7.138 1.66e-10 ***
## year          0.047154   0.006436   7.327 6.73e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.858 on 98 degrees of freedom
## Multiple R-squared:  0.3539, Adjusted R-squared:  0.3473 
## F-statistic: 53.68 on 1 and 98 DF,  p-value: 6.729e-11</code></pre>
<p>There is a strong, positive effect of observation year, with a slope estimate of 0.04, indicating that anomalies increase by 0.04 per year on average.</p>
<div class="sourceCode" id="cb575"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_ts</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, </span>
<span>             y <span class="op">=</span> <span class="va">anormaly</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>  <span class="co"># Set up the plot: x = year, y = anomaly</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span>     <span class="co"># Draw a dotted line connecting the points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span>           <span class="co"># Add points with transparency (alpha = 0.25)</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_lm</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,  <span class="co"># Add regression line from linear model</span></span>
<span>              slope <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">m_lm</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span>                             <span class="co"># Use a clean black-and-white theme</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-lm-fit-plot"></span>
<img src="biostats_files/figure-html/adv-06-lm-fit-plot-1.png" alt="Time-series of anomalies over years. Dotted lines connect consecutive observations, semi-transparent points show individual measurements, and the solid line represents the fitted linear trend from a linear regression model." width="672"><p class="caption">
Figure 22.2: Time-series of anomalies over years. Dotted lines connect consecutive observations, semi-transparent points show individual measurements, and the solid line represents the fitted linear trend from a linear regression model.
</p>
</div>
<p>The regression line may appear to fit the data well, with no obvious issues. However, if you think that, you have already fallen into a common pitfall of time-series analysis — this type of analysis has many potential problems.</p>
</div>
<div id="temporal-autocorrelation" class="section level3" number="22.1.2">
<h3>
<span class="header-section-number">22.1.2</span> Temporal autocorrelation<a class="anchor" aria-label="anchor" href="#temporal-autocorrelation"><i class="fas fa-link"></i></a>
</h3>
<p>While the data appear to show an increasing trend, this dataset was generated from a simulation that assumes NO true temporal increase — it was produced through a process known as a random walk.</p>
<p><span class="math display">\[
y_t = y_{t-1} + \varepsilon_{t}\\
\varepsilon_t \sim \text{Normal}(0, \sigma^2)
\]</span></p>
<p>This system is unique because each observation depends on its immediate past: the previous value (<span class="math inline">\(y_{t-1}\)</span>) plus noise (<span class="math inline">\(\varepsilon_t\)</span>) produces the current value (<span class="math inline">\(y_t\)</span>).</p>
<p>The behavior of a random walk is highly stochastic, producing very different patterns in each simulation run. You can observe this by running the following code, which generated the dataset shown above.</p>
<div class="sourceCode" id="cb576"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Initialize a vector to store the time series (100 time steps)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="cn">NA</span>, <span class="fl">100</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Generate random noise for each time step</span></span>
<span><span class="va">eps</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Set the initial condition of the time series</span></span>
<span><span class="va">y</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span></span>
<span><span class="co"># Generate a random walk:</span></span>
<span><span class="co"># each value equals the previous value plus random noise</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">t</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">y</span><span class="op">[</span><span class="va">t</span> <span class="op">+</span> <span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">y</span><span class="op">[</span><span class="va">t</span><span class="op">]</span> <span class="op">+</span> <span class="va">eps</span><span class="op">[</span><span class="va">t</span><span class="op">]</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Combine the time series with a corresponding year variable</span></span>
<span><span class="va">df_y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  anormaly <span class="op">=</span> <span class="va">y</span>,</span>
<span>  year <span class="op">=</span> <span class="fl">1925</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot time-series anomalies (not shown)</span></span>
<span><span class="va">df_y</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>,</span>
<span>             y <span class="op">=</span> <span class="va">anormaly</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>              </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>             </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>               </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Year"</span>,              </span>
<span>    y <span class="op">=</span> <span class="st">"Anomaly"</span>            </span>
<span>  <span class="op">)</span></span></code></pre></div>
<p>This is expected because we are measuring the same object over time, so the observations are not independent. This leads to temporal autocorrelation, a feature that violates a fundamental assumption of many statistical methods — the independence of data points. Temporal autocorrelation can be assessed using the <code><a href="https://rdrr.io/r/stats/acf.html">acf()</a></code> function in R:</p>
<div class="sourceCode" id="cb577"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## Data must be ordered from the oldest observation to the most recent</span></span>
<span><span class="va">df_ts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">df_ts</span>, <span class="va">year</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/acf.html">acf</a></span><span class="op">(</span><span class="va">df_ts</span><span class="op">$</span><span class="va">anormaly</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-acf-plot"></span>
<img src="biostats_files/figure-html/adv-06-acf-plot-1.png" alt="Autocorrelation function plot. The x-axis represents the lag, or the time difference between observations (e.g., lag 1 is the correlation between consecutive observations, lag 2 is two steps apart, etc.), while the y-axis shows the autocorrelation coefficient, ranging from -1 to 1, indicating how strongly observations at that lag are correlated." width="672"><p class="caption">
Figure 22.3: Autocorrelation function plot. The x-axis represents the lag, or the time difference between observations (e.g., lag 1 is the correlation between consecutive observations, lag 2 is two steps apart, etc.), while the y-axis shows the autocorrelation coefficient, ranging from -1 to 1, indicating how strongly observations at that lag are correlated.
</p>
</div>
<p>In an ACF (autocorrelation function) plot, the x-axis represents the lag, or the time difference between observations (e.g., lag 1 is the correlation between consecutive observations, lag 2 is two steps apart, etc.), while the y-axis shows the autocorrelation coefficient, ranging from -1 to 1, indicating how strongly observations at that lag are correlated.</p>
<p>Positive values mean observations tend to move in the same direction as previous ones, negative values indicate opposite movement, and values near zero suggest little or no correlation. The dashed lines represent approximate confidence bounds, so spikes outside these lines indicate statistically significant correlations at that lag.</p>
<p>Treating temporally correlated measurements as independent can seriously compromise statistical inference and lead to unsupported conclusions.</p>
<p>Below, we explore how to accommodate the challenging nature of time-series data using basic models, and how these models can be extended to assess the influence of external factors that also change over time in biological data analysis.</p>
</div>
</div>
<div id="basic-models" class="section level2" number="22.2">
<h2>
<span class="header-section-number">22.2</span> Basic Models<a class="anchor" aria-label="anchor" href="#basic-models"><i class="fas fa-link"></i></a>
</h2>
<p>As a starting point, we will focus on AR, MA, and ARMA models, all of which assume a stationary process. We will then extend these frameworks to the ARIMA model, which incorporates an integration step to handle non-stationary time series.</p>
<p>Stationarity is a fundamental concept in time-series analysis: a stationary process has a constant mean, variance, and autocorrelation structure over time. Non-stationarity means that one or more of these properties change through time—for example, the series may exhibit trends, shifts in variability, or evolving temporal dependence—making direct modeling and inference more challenging without first transforming the data.</p>
<p>We will use the built-in <code>LakeHuron</code> dataset to learn the implementation of these modeling approaches. All of the models discussed above can be implemented using the <code>Arima()</code> function from the <code>forecast</code> package, since AR, MA, and ARMA models are all special cases of the more general ARIMA framework.</p>
<div class="sourceCode" id="cb578"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create a tibble (modern data frame) from the LakeHuron time series</span></span>
<span><span class="va">df_huron</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  year <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/time.html">time</a></span><span class="op">(</span><span class="va">LakeHuron</span><span class="op">)</span>,                <span class="co"># Extracts the time component (years) from the LakeHuron ts object</span></span>
<span>  water_level <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">LakeHuron</span><span class="op">)</span>    <span class="co"># Converts LakeHuron values to numeric (from ts class)</span></span>
<span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span>                           <span class="co"># Ensures the data is ordered by year</span></span>
<span></span>
<span><span class="co"># Plot Lake Huron time series with a linear trend</span></span>
<span><span class="va">df_huron</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">water_level</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span>       <span class="co"># Semi-transparent points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Dotted line connecting points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,       <span class="co"># Linear trend line</span></span>
<span>              color <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>              linewidth <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Year"</span>, y <span class="op">=</span> <span class="st">"Water Level"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-huron-plot"></span>
<img src="biostats_files/figure-html/adv-06-huron-plot-1.png" alt="Time series of Lake Huron water levels from 1875 to 1972. Points represent annual water levels, and the dotted line connects consecutive observations. The solid black line shows a linear trend for reference only, providing a visual guide to the overall direction of change and facilitating comparison with predictions from time-series models." width="672"><p class="caption">
Figure 22.4: Time series of Lake Huron water levels from 1875 to 1972. Points represent annual water levels, and the dotted line connects consecutive observations. The solid black line shows a linear trend for reference only, providing a visual guide to the overall direction of change and facilitating comparison with predictions from time-series models.
</p>
</div>
<div id="ar-model" class="section level3" number="22.2.1">
<h3>
<span class="header-section-number">22.2.1</span> AR Model<a class="anchor" aria-label="anchor" href="#ar-model"><i class="fas fa-link"></i></a>
</h3>
<p>An autoregressive (AR) model describes a time series in which the current value depends on one or more of its past values plus random noise.</p>
<p><span class="math display">\[
y_t = \mu + \sum_{i=1}^p \phi_i y_{t - i} + \varepsilon_t
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the constant term (intercept), <span class="math inline">\(\phi_i\)</span> is the autoregressive parameter, and <span class="math inline">\(\varepsilon_t\)</span> is the (white) noise.</p>
<p>In an AR(<span class="math inline">\(p\)</span>) model, the present observation is a linear combination of the previous <span class="math inline">\(p\)</span> observations. The <span class="math inline">\(p\)</span> is referred to as the order of the model. AR models are stationary when the sum of autoregressive parameters <span class="math inline">\(\sum_i \phi_i\)</span> are less than one – this is analogous to population models with a carrying capacity in ecology.</p>
<p>In practice, we supply a vector of time-series data to the <code><a href="https://rdrr.io/r/stats/arima.html">arima()</a></code> function. We will begin with the simplest autoregressive model of order one, which is specified by setting the first element of the <code>order</code> argument to 1 (i.e., <code>order = c(1, 0, 0)</code>).</p>
<div class="sourceCode" id="cb579"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">m_ar1</span> <span class="op">&lt;-</span> <span class="fu">Arima</span><span class="op">(</span></span>
<span>  <span class="va">df_huron</span><span class="op">$</span><span class="va">water_level</span>,       <span class="co"># The time series data we want to model</span></span>
<span>  order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span>          <span class="co"># ARIMA model orders: c(p, d, q)</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_huron$water_level 
## ARIMA(1,0,0) with non-zero mean 
## 
## Coefficients:
##          ar1      mean
##       0.8375  579.1153
## s.e.  0.0538    0.4240
## 
## sigma^2 = 0.5199:  log likelihood = -106.6
## AIC=219.2   AICc=219.45   BIC=226.95</code></pre>
<p>This setup corresponds to setting the order (<span class="math inline">\(p = 1\)</span>) in an AR model, meaning the process “remembers” the previous observation. The remaining elements of the <code>order</code> argument define the other components of the model, which are relevant for the additional models introduced below.</p>
<p>We can extract the in-sample fitted values from the AR(1) model using the <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> function. Below, we compare these model predictions with a simple linear trend to illustrate how the time-series model captures temporal dependence beyond what a linear model provides.</p>
<div class="sourceCode" id="cb581"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Add fitted values from AR(1) model to the dataset</span></span>
<span><span class="va">df_huron_ar1</span> <span class="op">&lt;-</span> <span class="va">df_huron</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_ar1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>   <span class="co"># Extract fitted (in-sample predicted) values from the AR(1) model</span></span>
<span>           <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>           <span class="co"># Convert to numeric if necessary</span></span>
<span></span>
<span><span class="co"># Plot observed and fitted values</span></span>
<span><span class="va">df_huron_ar1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, </span>
<span>                 y <span class="op">=</span> <span class="va">water_level</span><span class="op">)</span>,</span>
<span>             alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span>        <span class="co"># Plot observed water levels</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, </span>
<span>                y <span class="op">=</span> <span class="va">fit</span><span class="op">)</span>,           <span class="co"># Plot AR(1) fitted values</span></span>
<span>            color <span class="op">=</span> <span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span>                        <span class="co"># Clean black-and-white theme</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-ar1-plot"></span>
<img src="biostats_files/figure-html/adv-06-ar1-plot-1.png" alt="Observed Lake Huron water levels (points) with in-sample fitted values from an AR(1) model (steelblue line). The AR(1) model captures temporal dependence in the series, providing a better representation of year-to-year variation than a simple linear trend." width="672"><p class="caption">
Figure 22.5: Observed Lake Huron water levels (points) with in-sample fitted values from an AR(1) model (steelblue line). The AR(1) model captures temporal dependence in the series, providing a better representation of year-to-year variation than a simple linear trend.
</p>
</div>
<p>AR models assume stationarity, meaning their expected values and variance remain constant over time. When projecting time-series data into the future, AR models can produce forecasts that account for temporal dependence, often giving a very different and more realistic picture than a simple linear trend.</p>
<p>The <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function preforms the projection with the <code>n.ahead</code> argument.</p>
<div class="sourceCode" id="cb582"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Add in-sample fitted values</span></span>
<span><span class="va">df_huron_ar1</span> <span class="op">&lt;-</span> <span class="va">df_huron</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m_ar1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Forecast the next 50 time points using the AR(1) model</span></span>
<span><span class="va">df_pred_ar1</span> <span class="op">&lt;-</span> <span class="fu">forecast</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/forecast.html">forecast</a></span><span class="op">(</span><span class="va">m_ar1</span>, h <span class="op">=</span> <span class="fl">50</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span>rownames <span class="op">=</span> <span class="st">"year"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>year <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">df_huron</span><span class="op">$</span><span class="va">year</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="va">point_forecast</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Combine historical AR(1) fitted values and future forecasts, then plot</span></span>
<span><span class="va">df_huron_ar1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">df_pred_ar1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">water_level</span><span class="op">)</span>,  <span class="co"># Observed water levels (semi-transparent)</span></span>
<span>             alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>,                   <span class="co"># Visualize forecast uncertainty</span></span>
<span>                  ymin <span class="op">=</span> <span class="va">lo_95</span>,</span>
<span>                  ymax <span class="op">=</span> <span class="va">hi_95</span><span class="op">)</span>,</span>
<span>              fill <span class="op">=</span> <span class="st">"grey"</span>,</span>
<span>              color <span class="op">=</span> <span class="cn">NA</span>,</span>
<span>              alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">fit</span><span class="op">)</span>,           <span class="co"># Fitted values for historical data + forecasts</span></span>
<span>            color <span class="op">=</span> <span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Year"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Water Level"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-ar1-plot-pred"></span>
<img src="biostats_files/figure-html/adv-06-ar1-plot-pred-1.png" alt="Observed Lake Huron water levels (points) with AR(1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confidence intervals around the predictions, illustrating the uncertainty of the forecast. This visualization highlights how the AR(1) model captures temporal dependence and projects future values differently from a simple linear trend." width="672"><p class="caption">
Figure 22.6: Observed Lake Huron water levels (points) with AR(1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confidence intervals around the predictions, illustrating the uncertainty of the forecast. This visualization highlights how the AR(1) model captures temporal dependence and projects future values differently from a simple linear trend.
</p>
</div>
</div>
<div id="ma-model" class="section level3" number="22.2.2">
<h3>
<span class="header-section-number">22.2.2</span> MA Model<a class="anchor" aria-label="anchor" href="#ma-model"><i class="fas fa-link"></i></a>
</h3>
<p>A moving average (MA) model represents a time series as a function of past random noises rather than past observations. In an MA(q) model, the current value depends on the current and previous q error terms.</p>
<p><span class="math display">\[
y_t = \mu + \sum_{i=1}^q \theta_i \varepsilon_{t-i} + \varepsilon_t
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the constant term (intercept), <span class="math inline">\(\theta_i\)</span> is the moving-average parameter, and <span class="math inline">\(\varepsilon_t\)</span> is the (white) noise. In the <code>Arima()</code> function, specifying <code>order = c(0, 0, 1)</code> corresponds to a moving-average model of order 1 (MA(1)), where the current value depends on the most recent random noise.</p>
<div class="sourceCode" id="cb583"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">m_ma1</span> <span class="op">&lt;-</span> <span class="fu">Arima</span><span class="op">(</span></span>
<span>  <span class="va">df_huron</span><span class="op">$</span><span class="va">water_level</span>,       <span class="co"># The time series data we want to model</span></span>
<span>  order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>          <span class="co"># ARIMA model orders: c(p, d, q)</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_huron$water_level 
## ARIMA(0,0,1) with non-zero mean 
## 
## Coefficients:
##          ma1      mean
##       0.8302  578.9982
## s.e.  0.0633    0.1580
## 
## sigma^2 = 0.7517:  log likelihood = -124.65
## AIC=255.3   AICc=255.55   BIC=263.05</code></pre>
<p>We can perform a similar fitting, forecasting, and visualization for MA models, which highlights how their behavior differs from AR models. In particular, the average of the projected values quickly converges to the average of observed values.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-ma1-plot"></span>
<img src="biostats_files/figure-html/adv-06-ma1-plot-1.png" alt="Observed Lake Huron water levels (points) with MA(1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confidence intervals around the predictions, illustrating the uncertainty of the forecast." width="672"><p class="caption">
Figure 22.7: Observed Lake Huron water levels (points) with MA(1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confidence intervals around the predictions, illustrating the uncertainty of the forecast.
</p>
</div>
<p>This convergence occurs because MA models capture autocorrelation in the error terms, but the current value does not directly depend on past observations, unlike AR models.</p>
</div>
<div id="arma-model" class="section level3" number="22.2.3">
<h3>
<span class="header-section-number">22.2.3</span> ARMA Model<a class="anchor" aria-label="anchor" href="#arma-model"><i class="fas fa-link"></i></a>
</h3>
<p>An ARMA model combines both autoregressive and moving-average components, allowing the current value to depend on both past observations and past random noises.</p>
<p><span class="math display">\[
y_t = \mu + \sum_{i=1}^p\phi_i y_{t-i} + \sum_{i=1}^q \theta_i\varepsilon_{t-i} + \varepsilon_t
\]</span></p>
<p>The parameters are defined as above. Since an ARMA model combines both AR and MA components, we specify <code>order = c(1, 0, 1)</code> to include first-order AR and MA terms, allowing the current value to depend on both the previous observation and the most recent random noise.</p>
<div class="sourceCode" id="cb585"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">m_arma</span> <span class="op">&lt;-</span> <span class="fu">Arima</span><span class="op">(</span></span>
<span>  <span class="va">df_huron</span><span class="op">$</span><span class="va">water_level</span>,       <span class="co"># The time series data we want to model</span></span>
<span>  order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>          <span class="co"># ARIMA model orders: c(p, d, q)</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_huron$water_level 
## ARIMA(1,0,1) with non-zero mean 
## 
## Coefficients:
##          ar1     ma1      mean
##       0.7449  0.3206  579.0555
## s.e.  0.0777  0.1135    0.3501
## 
## sigma^2 = 0.4899:  log likelihood = -103.25
## AIC=214.49   AICc=214.92   BIC=224.83</code></pre>
<p>We can visualize the ARMA(1,1) model in the same way as we did for the AR(1) and MA(1) models by combining historical fitted values with out-of-sample forecasts and displaying the uncertainty:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-arma-plot"></span>
<img src="biostats_files/figure-html/adv-06-arma-plot-1.png" alt="Observed Lake Huron water levels (points) with ARMA(1,1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confindence intervals around the predictions, illustrating the uncertainty of the forecast." width="672"><p class="caption">
Figure 22.8: Observed Lake Huron water levels (points) with ARMA(1,1) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confindence intervals around the predictions, illustrating the uncertainty of the forecast.
</p>
</div>
</div>
<div id="arima-model" class="section level3" number="22.2.4">
<h3>
<span class="header-section-number">22.2.4</span> ARIMA model<a class="anchor" aria-label="anchor" href="#arima-model"><i class="fas fa-link"></i></a>
</h3>
<p>An ARIMA model can be thought of as an ARMA model applied to the differenced series. To illustrate, consider an ARIMA model with first-order differencing. We define a new variable: <span class="math inline">\(\delta_t = y_t - y_{t-1}\)</span>.</p>
<p>The ARIMA then fits an ARMA(p, q) model to <span class="math inline">\(\delta_t\)</span>, capturing the autoregressive and moving-average structure in the differenced (stationary) series:</p>
<p><span class="math display">\[
\delta_t = \sum_{i=1}^p \phi_i \delta_{t-i} + \sum_{i=1}^q \theta_i \varepsilon_{t-i} +\varepsilon_t
\]</span></p>
<p>This is a special case of the more general d-order ARIMA(p,d,q) model, specifically ARIMA(p,1,q) where <span class="math inline">\(d=1\)</span>. For more detailed explanations and examples, you can refer to well-developed documentation, such as <a href="https://en.wikipedia.org/wiki/Autoregressive_integrated_moving_average">Wikipedia</a></p>
<p>This extension allows ARIMA models to handle non-stationary time series, where the mean or trend changes over time. Here, we assume <span class="math inline">\(p=1\)</span> and <span class="math inline">\(d=1\)</span> to illustrate and gain insights into how the ARIMA model operates.</p>
<div class="sourceCode" id="cb587"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">m_arima</span> <span class="op">&lt;-</span> <span class="fu">Arima</span><span class="op">(</span><span class="va">df_huron</span><span class="op">$</span><span class="va">water_level</span>,</span>
<span>                  order <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_huron$water_level 
## ARIMA(1,1,0) 
## 
## Coefficients:
##          ar1
##       0.1362
## s.e.  0.1021
## 
## sigma^2 = 0.5544:  log likelihood = -108.23
## AIC=220.45   AICc=220.58   BIC=225.6</code></pre>
<p>No constant term is estimated because the series is first-order differenced. The visualization highlights how the shifting mean influences the model’s projections over time – the uncertainty is greater than stationary models.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-arima-plot"></span>
<img src="biostats_files/figure-html/adv-06-arima-plot-1.png" alt="Observed Lake Huron water levels (points) with ARIMA(1,1,0) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confindence intervals around the predictions, illustrating forecast uncertainty." width="672"><p class="caption">
Figure 22.9: Observed Lake Huron water levels (points) with ARIMA(1,1,0) model fitted values and 50-year forecasts (steelblue line). The shaded grey ribbon represents 95% confindence intervals around the predictions, illustrating forecast uncertainty.
</p>
</div>
</div>
<div id="model-selection" class="section level3" number="22.2.5">
<h3>
<span class="header-section-number">22.2.5</span> Model selection<a class="anchor" aria-label="anchor" href="#model-selection"><i class="fas fa-link"></i></a>
</h3>
<p>Selecting the appropriate model and its orders can be challenging, because there are multiple model types (AR, MA, ARMA, ARIMA) and many possible combinations of parameters (p, d, q). One common approach to guide model selection is the use of information criteria, such as the Akaike Information Criterion (AIC), which balance model fit and complexity.</p>
<p>This approach is conveniently implemented in the <code>forecast</code> package. In particular, the function <code>auto.arima()</code> automatically searches over a range of ARIMA models and selects the combination of parameters that yields the most parsimonious model for your data, simplifying the model selection process.</p>
<div class="sourceCode" id="cb589"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Possible extensions / additional arguments:</span></span>
<span><span class="co"># max.p, max.q       : maximum AR and MA orders to consider</span></span>
<span><span class="co"># d, D               : specify non-seasonal or seasonal differencing (or let auto.arima decide)</span></span>
<span><span class="co"># seasonal           : include seasonal ARIMA components (TRUE/FALSE)</span></span>
<span><span class="co"># max.P, max.Q       : maximum seasonal AR and MA orders</span></span>
<span><span class="co"># approximation      : use approximation for faster computation on long series</span></span>
<span><span class="co"># lambda             : Box-Cox transformation for stabilizing variance</span></span>
<span></span>
<span><span class="fu">auto.arima</span><span class="op">(</span></span>
<span>  <span class="va">df_huron</span><span class="op">$</span><span class="va">water_level</span>, <span class="co"># data</span></span>
<span>  stepwise <span class="op">=</span> <span class="cn">FALSE</span>,  <span class="co"># stepwise = FALSE: search all possible models rather than using stepwise approximation</span></span>
<span>  ic <span class="op">=</span> <span class="st">"aic"</span> <span class="co"># model selection based on AIC</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_huron$water_level 
## ARIMA(2,1,1) 
## 
## Coefficients:
##          ar1      ar2      ma1
##       0.9712  -0.2924  -0.9108
## s.e.  0.1137   0.1030   0.0712
## 
## sigma^2 = 0.5003:  log likelihood = -102.54
## AIC=213.07   AICc=213.51   BIC=223.37</code></pre>
<p>In this case, ARIMA(2,1,1) was selected, which suggests a non-stationary series with a shifting mean (due to differencing) and autocorrelations in the changes captured by the AR and MA terms.</p>
</div>
</div>
<div id="applied-models" class="section level2" number="22.3">
<h2>
<span class="header-section-number">22.3</span> Applied Models<a class="anchor" aria-label="anchor" href="#applied-models"><i class="fas fa-link"></i></a>
</h2>
<p>While the time-series models introduced above allow us to account for temporal autocorrelation, our primary interest is often in how external variables influence the response. How, then, can we incorporate predictors into a time-series model?</p>
<p>Recall that a linear model has the following structure when predictors <span class="math inline">\(x\)</span> are included:</p>
<p><span class="math display">\[
y_i = \alpha + \sum_k \beta_k x_{i}^{(k)} + \varepsilon_i
\]</span></p>
<p>where <span class="math inline">\(\alpha\)</span> is the intercept, and <span class="math inline">\(\beta\)</span> is the slope. In this framework, we assume that the error term <span class="math inline">\(\varepsilon_i\)</span> is independent across observations with <span class="math inline">\(\varepsilon_i \sim \text{Normal}(0, \sigma^2)\)</span>.</p>
<p>However, because we assume independence in the error term, problems arise when the data exhibit temporal autocorrelation. If we model the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> as if the observations are independent, the effect of <span class="math inline">\(x\)</span> can be estimated as artificially significant, increasing the risk of a Type I error; that is, we may conclude that <span class="math inline">\(x\)</span> has a significant effect even when it does not.</p>
<p>We can include ARIMA components in the error term to account for temporal autocorrelation before evaluating the effects of external predictors. For example, if the error term follows an ARMA process, the model can be written as:</p>
<p><span class="math display">\[
y_t = \alpha + \sum_k \beta_k x_{t}^{(k)} + u_t\\
u_t = \underbrace{\sum_{i=1}^p \phi_i y_{t - i}}_{\text{AR}} + \underbrace{\sum_{i = 1}^q \theta_i \varepsilon_{t - i}}_{\text{MA}} + \underbrace{\varepsilon_t}_{\text{Noise}}
\]</span>R offers a variety of functions for performing this type of modeling. Let’s explore how it works in practice.</p>
<div id="arimax" class="section level3" number="22.3.1">
<h3>
<span class="header-section-number">22.3.1</span> ARIMAX<a class="anchor" aria-label="anchor" href="#arimax"><i class="fas fa-link"></i></a>
</h3>
<p>ARIMAX is an ARIMA model that includes external predictors. To illustrate its use, we use ice-cover data from Lake Mendota, Wisconsin, available in the <code>lmerdatasampler</code> R package. We focus on the period from 1980 to 2014 (35 years).</p>
<div class="sourceCode" id="cb591"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Load and inspect the dataset</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"ntl_icecover"</span><span class="op">)</span>  <span class="co"># Built-in dataset with ice cover information for multiple lakes</span></span>
<span></span>
<span><span class="co"># Convert to tibble and filter for a specific lake and years &gt;= 1980</span></span>
<span><span class="va">df_ice</span> <span class="op">&lt;-</span> <span class="va">ntl_icecover</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Convert to tibble for tidyverse-friendly operations</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/between.html">between</a></span><span class="op">(</span><span class="va">year</span>, <span class="fl">1980</span>, <span class="fl">2014</span><span class="op">)</span>, <span class="co"># Keep only years from 1980 onward</span></span>
<span>         <span class="va">lakeid</span> <span class="op">==</span> <span class="st">"Lake Mendota"</span><span class="op">)</span> <span class="co"># Keep only data for Lake Mendota</span></span>
<span></span>
<span><span class="co"># Create a line + point plot of ice duration over time</span></span>
<span><span class="va">df_ice</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, <span class="co"># Year on x-axis</span></span>
<span>             y <span class="op">=</span> <span class="va">ice_duration</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Ice duration (days) on y-axis</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Add a dotted line connecting points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Add semi-transparent points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Use a clean black-and-white theme</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Ice duration"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Year"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-mendota-plot"></span>
<img src="biostats_files/figure-html/adv-06-mendota-plot-1.png" alt="Ice-cover data for Lake Mendota (1980–2014) visualized as a dotted line with semi-transparent points. This plot shows the temporal trajectory of ice duration over 35 years, highlighting interannual variability." width="672"><p class="caption">
Figure 22.10: Ice-cover data for Lake Mendota (1980–2014) visualized as a dotted line with semi-transparent points. This plot shows the temporal trajectory of ice duration over 35 years, highlighting interannual variability.
</p>
</div>
<p>We will explore how ice-cover duration varies with air temperature. Daily temperature data can be obtained from <a href="https://daymet.ornl.gov/">DAYMET</a>, and the <code>daymetr</code> R package allows you to download these data directly into R.</p>
<div class="sourceCode" id="cb592"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Download daily climate data from Daymet for Lake Mendota</span></span>
<span><span class="va">list_mendota</span> <span class="op">&lt;-</span> <span class="fu">download_daymet</span><span class="op">(</span></span>
<span>  site <span class="op">=</span> <span class="st">"Lake_Mendota"</span>,   <span class="co"># Arbitrary name you assign to this site</span></span>
<span>  lat <span class="op">=</span> <span class="fl">43.1</span>,              <span class="co"># Latitude of the lake</span></span>
<span>  lon <span class="op">=</span> <span class="op">-</span><span class="fl">89.4</span>,             <span class="co"># Longitude of the lake</span></span>
<span>  start <span class="op">=</span> <span class="fl">1980</span>,            <span class="co"># Start year</span></span>
<span>  end <span class="op">=</span> <span class="fl">2024</span>,              <span class="co"># End year</span></span>
<span>  internal <span class="op">=</span> <span class="cn">TRUE</span>          <span class="co"># Return the data as an R object rather than saving to disk</span></span>
<span><span class="op">)</span></span></code></pre></div>
<p>Because the original data format is difficult to work with, we will transform it into a structure compatible with the tidyverse framework. The following code calculates the average daily-minimum temperature.</p>
<div class="sourceCode" id="cb593"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_temp</span> <span class="op">&lt;-</span> <span class="va">list_mendota</span><span class="op">$</span><span class="va">data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>                  <span class="co"># Convert the data to a tibble for tidyverse-friendly operations</span></span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>       <span class="co"># Clean column names (lowercase, underscores)</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># Create a proper Date object from year and day-of-year</span></span>
<span>    date <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">yday</span>, sep <span class="op">=</span> <span class="st">"-"</span><span class="op">)</span>, format <span class="op">=</span> <span class="st">"%Y-%j"</span><span class="op">)</span>,</span>
<span>    <span class="co"># Extract the month from the date</span></span>
<span>    month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">yday</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Group by year</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>temp_min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">tmin_deg_c</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="co"># Compute average daily minimum temperature</span></span></code></pre></div>
<p>We can now join the temperature data with the ice-duration data, enabling analysis of how air temperature influences ice-cover duration.</p>
<div class="sourceCode" id="cb594"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Join the temperature data to the ice cover data by year</span></span>
<span><span class="va">df_ice</span> <span class="op">&lt;-</span> <span class="va">df_ice</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">df_temp</span>, by <span class="op">=</span> <span class="st">"year"</span><span class="op">)</span></span></code></pre></div>
<p>The <code>Arima()</code> and <code>auto.arima()</code> functions include an <code>xreg</code> argument, which allows us to supply potential predictor variables. <code>xreg</code> can be a vector or a matrix, but it must have the same number of rows as the response time series (ice duration in our case).</p>
<div class="sourceCode" id="cb595"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">obj_arima</span> <span class="op">&lt;-</span> <span class="fu">auto.arima</span><span class="op">(</span></span>
<span>  <span class="va">df_ice</span><span class="op">$</span><span class="va">ice_duration</span>, <span class="co"># Response variable: ice duration time series</span></span>
<span>  xreg <span class="op">=</span> <span class="va">df_ice</span><span class="op">$</span><span class="va">temp_min</span>, <span class="co"># External predictor: average minimum temperature</span></span>
<span>  stepwise <span class="op">=</span> <span class="cn">FALSE</span> <span class="co"># Use exhaustive search instead of stepwise approximation for model selection</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Series: df_ice$ice_duration 
## Regression with ARIMA(1,0,0) errors 
## 
## Coefficients:
##           ar1  intercept     xreg
##       -0.4650   107.3676  -8.0622
## s.e.   0.1484     6.6398   2.6708
## 
## sigma^2 = 364.5:  log likelihood = -151.44
## AIC=310.89   AICc=312.22   BIC=317.11</code></pre>
<p>The ARIMAX output now includes the estimated coefficient for the external predictor (<code>xreg</code>) along with the selected model structure (AR(1)). This coefficient represents the impact of temperature on ice-cover duration and appears to be highly significant, with an estimate of -8.06 and a standard error of 2.67.<br></p>
<p>We can also compute confidence intervals to obtain more detailed information about the uncertainty around this estimate. If the 95% confidence interval (CI) for a coefficient does not include zero, the estimate is considered statistically significant and highly reliable.</p>
<div class="sourceCode" id="cb597"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">obj_arima</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                 2.5 %      97.5 %
## ar1        -0.7559461  -0.1741116
## intercept  94.3538337 120.3814411
## xreg      -13.2967927  -2.8276105</code></pre>
<p>In our case, the 95% confidence interval for the <code>xreg</code> coefficient (temperature effect) is entirely negative and does not overlap zero, indicating that ice duration decreases significantly as winter temperature increases.</p>
<p>Including predictor variables makes the forecast more meaningful. Although our model was fitted to data from 1980–2014, we have temperature observations for 2015–2024. While we use these observed temperatures in this exercise, the predictor values could also come from model outputs, such as climate model projections, allowing us to explore potential impacts of climate change.</p>
<div class="sourceCode" id="cb599"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 1. Add fitted values from the ARIMAX model to the original ice-cover dataset</span></span>
<span><span class="va">df_ice</span> <span class="op">&lt;-</span> <span class="va">df_ice</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">obj_arima</span><span class="op">)</span><span class="op">)</span> <span class="co"># 'fitted()' gives the model's in-sample predicted values</span></span>
<span></span>
<span><span class="co"># 2. Prepare new temperature data for forecasting</span></span>
<span><span class="va">v_temp</span> <span class="op">&lt;-</span> <span class="va">df_temp</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">&gt;</span> <span class="fl">2014</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Select years beyond the original modeling period</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">temp_min</span><span class="op">)</span> <span class="co"># Extract the temperature values as a numeric vector</span></span>
<span></span>
<span><span class="co"># 3. Forecast ice duration for 2015–2024 using ARIMAX model with new temperature values</span></span>
<span><span class="va">df_fore</span> <span class="op">&lt;-</span> <span class="fu">forecast</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/forecast.html">forecast</a></span><span class="op">(</span><span class="va">obj_arima</span>, xreg <span class="op">=</span> <span class="va">v_temp</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Forecast with external predictor</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Convert forecast object to tibble</span></span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Clean column names</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="va">point_forecast</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Rename point forecast column to 'fit'</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>year <span class="op">=</span> <span class="fl">2015</span><span class="op">:</span><span class="fl">2024</span><span class="op">)</span> <span class="co"># Add year column for alignment</span></span>
<span></span>
<span><span class="co"># 4. Combine historical data with forecasted data</span></span>
<span><span class="va">df_ice</span> <span class="op">&lt;-</span> <span class="va">df_ice</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">df_fore</span><span class="op">)</span>  <span class="co"># Append forecasted years to the original dataset</span></span></code></pre></div>
<p>Because we include temperature as a predictor, the forecast is no longer constant but varies according to future temperature values.</p>
<div class="sourceCode" id="cb600"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Combine historical fitted values and forecasts, then plot</span></span>
<span><span class="va">df_ice</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># 1. Observed ice duration points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">ice_duration</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="co"># 2. 95% confidence interval ribbon for forecasted values</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, ymin <span class="op">=</span> <span class="va">lo_95</span>, ymax <span class="op">=</span> <span class="va">hi_95</span><span class="op">)</span>,</span>
<span>              fill <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="co"># 3. 80% confidence interval ribbon for forecasted values</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, ymin <span class="op">=</span> <span class="va">lo_80</span>, ymax <span class="op">=</span> <span class="va">hi_80</span><span class="op">)</span>,</span>
<span>              fill <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="co"># 4. Line showing fitted values (historical + forecast)</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>, y <span class="op">=</span> <span class="va">fit</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span>  </span>
<span>  <span class="co"># 5. Clean theme</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># 6. Axis labels</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Year"</span>, y <span class="op">=</span> <span class="st">"Ice duration"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-arimax-plot"></span>
<img src="biostats_files/figure-html/adv-06-arimax-plot-1.png" alt="Historical ice-cover duration (points) and ARIMAX model predictions (blue line) for Lake Mendota, including forecasts for 2015–2024. Shaded ribbons show the 80% and 95% confidence intervals for the forecasts. Because temperature is included as a predictor, the forecast varies with future temperature values rather than remaining constant." width="672"><p class="caption">
Figure 22.11: Historical ice-cover duration (points) and ARIMAX model predictions (blue line) for Lake Mendota, including forecasts for 2015–2024. Shaded ribbons show the 80% and 95% confidence intervals for the forecasts. Because temperature is included as a predictor, the forecast varies with future temperature values rather than remaining constant.
</p>
</div>
</div>
<div id="glarma" class="section level3" number="22.3.2">
<h3>
<span class="header-section-number">22.3.2</span> GLARMA<a class="anchor" aria-label="anchor" href="#glarma"><i class="fas fa-link"></i></a>
</h3>
<p>One major limitation of ARIMAX models is their assumption of normally distributed errors, which makes them unsuitable for non-normal data. To overcome this, the Generalized Linear ARMA (GLARMA) model was developed, analogous to the extension from linear models to generalized linear models.</p>
<p>In our next example, we analyze fish count data for Cutthroat Trout from Mack Creek, Oregon. Because these are count data, modeling the temporal process using a normal distribution would be inappropriate, making GLARMA a more suitable choice.</p>
<div class="sourceCode" id="cb601"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Load HJ Andrews LTER vertebrate survey data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"and_vertebrates"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_ct</span> <span class="op">&lt;-</span> <span class="va">and_vertebrates</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">species</span> <span class="op">==</span> <span class="st">"Cutthroat trout"</span>,</span>
<span>         <span class="va">length_1_mm</span> <span class="op">&gt;</span> <span class="fl">160</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>  <span class="co"># Keep only large cutthroat trout (hypothetical matured adults)</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Group records by year</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, <span class="co"># Count number of captures per year</span></span>
<span>            .groups <span class="op">=</span> <span class="st">"drop"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_ct</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">year</span>,</span>
<span>             y <span class="op">=</span> <span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Year"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="biostats_files/figure-html/adv-06-mack-data-1.png" width="672" style="display: block; margin: auto;"></div>
<p>Cutthroat Trout is a cold-water species, so summer maximum temperature may be an important predictor of its abundance. To investigate this, we obtained climate data for Mack Creek from DAYMET.</p>
<div class="sourceCode" id="cb602"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Download daily climate data from Daymet for Lake Mendota</span></span>
<span><span class="va">list_mack</span> <span class="op">&lt;-</span> <span class="fu">download_daymet</span><span class="op">(</span></span>
<span>  site <span class="op">=</span> <span class="st">"Mack_Creek"</span>,   <span class="co"># Arbitrary name you assign to this site</span></span>
<span>  lat <span class="op">=</span> <span class="fl">44.2276</span>,         <span class="co"># Latitude of the lake</span></span>
<span>  lon <span class="op">=</span> <span class="op">-</span><span class="fl">122.1673</span>,       <span class="co"># Longitude of the lake</span></span>
<span>  start <span class="op">=</span> <span class="fl">1987</span>,          <span class="co"># Start year</span></span>
<span>  end <span class="op">=</span> <span class="fl">2019</span>,            <span class="co"># End year</span></span>
<span>  internal <span class="op">=</span> <span class="cn">TRUE</span>        <span class="co"># Return the data as an R object rather than saving to disk</span></span>
<span><span class="op">)</span></span></code></pre></div>
<p>As in the ARIMAX example, we can summarize summer temperature data using date as the reference.</p>
<div class="sourceCode" id="cb603"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_stemp</span> <span class="op">&lt;-</span> <span class="va">list_mack</span><span class="op">$</span><span class="va">data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    date <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">yday</span>, sep <span class="op">=</span> <span class="st">"-"</span><span class="op">)</span>, format <span class="op">=</span> <span class="st">"%Y-%j"</span><span class="op">)</span>,</span>
<span>    month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">date</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">month</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6</span><span class="op">:</span><span class="fl">8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># Select only summer months</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>temp_max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">tmax_deg_c</span><span class="op">)</span><span class="op">)</span> <span class="co"># Averaging daily max temperature</span></span>
<span></span>
<span><span class="co"># Add annual precipitation data by matching on year</span></span>
<span><span class="va">df_ct</span> <span class="op">&lt;-</span> <span class="va">df_ct</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">df_stemp</span>,</span>
<span>            by <span class="op">=</span> <span class="st">"year"</span><span class="op">)</span></span></code></pre></div>
<p>The data format for <code>glarma()</code> is somewhat unique. The response variable must be provided as a vector, while the predictors (summer temperature in this case) must be supplied as a matrix. It is also essential to include a column for the intercept (a column of ones); without it, interpretation of model coefficients can be difficult.</p>
<p>The <code>type</code> argument specifies the error distribution for the response variable. Since we are modeling count data, our first choice is the Poisson distribution. (<code>type = "Poi"</code>).</p>
<p>The <code>phiLags</code> argument defines the order(s) of the AR process. Unlike the <code>Arima()</code> function, you can specify multiple AR orders separately—for example, 1 and 3, or 1 and 5. In this example, we will start with a first-order AR term as a baseline.</p>
<div class="sourceCode" id="cb604"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Response variable: annual cutthroat trout counts</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">df_ct</span><span class="op">$</span><span class="va">n</span> </span>
<span></span>
<span><span class="co"># Design matrix for mean structure</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="op">~</span> <span class="va">temp_max</span>, <span class="co"># Intercept + summer temperature predictor</span></span>
<span>                  data <span class="op">=</span> <span class="va">df_ct</span><span class="op">)</span></span>
<span></span>
<span><span class="va">obj_glarma</span> <span class="op">&lt;-</span> <span class="fu">glarma</span><span class="op">(</span></span>
<span>  y <span class="op">=</span> <span class="va">y</span>,                               <span class="co"># Count time series</span></span>
<span>  X <span class="op">=</span> <span class="va">X</span>,                               <span class="co"># GLM design matrix</span></span>
<span>  phiLags <span class="op">=</span> <span class="fl">1</span>,                         <span class="co"># AR structure in residuals (lag 1)</span></span>
<span>  type <span class="op">=</span> <span class="st">"Poi"</span>                         <span class="co"># Poisson to allow count data</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">obj_glarma</span><span class="op">)</span>                    <span class="co"># Model coefficients and diagnostics</span></span></code></pre></div>
<pre><code>## 
## Call: glarma(y = y, X = X, type = "Poi", phiLags = 1)
## 
## Pearson Residuals:
##     Min       1Q   Median       3Q      Max  
## -2.0852  -0.8918  -0.0879   1.0448   3.2881  
## 
## GLARMA Coefficients:
##       Estimate Std.Error z-ratio Pr(&gt;|z|)    
## phi_1   0.1644    0.0415   3.962 7.42e-05 ***
## 
## Linear Model Coefficients:
##             Estimate Std.Error z-ratio Pr(&gt;|z|)    
## (Intercept)  3.50886   0.91518   3.834 0.000126 ***
## temp_max    -0.05208   0.03614  -1.441 0.149537    
## 
##     Null deviance: 76.138  on 32  degrees of freedom
## Residual deviance: 53.679  on 30  degrees of freedom
## AIC: 191.0176 
## 
## Number of Fisher Scoring iterations: 30
## 
## LRT and Wald Test:
## Alternative hypothesis: model is a GLARMA process
## Null hypothesis: model is a GLM with the same regression structure
##           Statistic  p-value    
## LR Test       10.45  0.00123 ** 
## Wald Test     15.70 7.42e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The <code>Linear Model Coefficients</code> section can be interpreted much like the output of a standard GLM. The temperature effect is estimated to be insignificant - compare this result with the <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> function with Poisson errors, which would produce a significant effect of summer temperature (i.e., likely Type I error due to temporal autocorrelation)!</p>
<p>In addition, GLARMA provides extra sections – most notably, <code>GLARMA Coefficients</code> – which summarize the estimated autoregressive (AR) parameters. In our example, the first-order AR parameter, <code>phi_1</code>, is estimated at approximately 0.16. This parameter is estimated on the link scale; for a Poisson distribution, that corresponds to the log scale.</p>
<p>Unfortunately, the <code>glarma()</code> function does not include automated model selection. Therefore, we must choose and compare model orders manually. Here, we will explore different AR orders, from 1 to 3. The following code fits these three models and reports their AIC values for comparison.</p>
<div class="sourceCode" id="cb606"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">list_glarma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,</span>
<span>                      <span class="kw">function</span><span class="op">(</span><span class="va">o</span><span class="op">)</span> <span class="op">{</span></span>
<span>                        <span class="va">obj_glarma</span> <span class="op">&lt;-</span> <span class="fu">glarma</span><span class="op">(</span>y <span class="op">=</span> <span class="va">y</span>, </span>
<span>                                             X <span class="op">=</span> <span class="va">X</span>, </span>
<span>                                             phiLags <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">o</span><span class="op">)</span>,</span>
<span>                                             type <span class="op">=</span> <span class="st">"Poi"</span><span class="op">)</span></span>
<span>                      <span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">list_glarma</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span><span class="op">$</span><span class="va">aic</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [[1]]
## [1] 191.0176
## 
## [[2]]
## [1] 192.2589
## 
## [[3]]
## [1] 192.8682</code></pre>
<p>The AR(1) model has the lowest AIC, suggesting that our initial choice of a first-order autoregressive term was reasonable. As with the <code>Arima()</code> function, the GLARMA model allows us to obtain fitted values using the <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> function.</p>
<div class="sourceCode" id="cb608"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_ct</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>fit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">obj_glarma</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>  <span class="co"># Add GLARMA fitted values as a new column</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">year</span>,</span>
<span>    y <span class="op">=</span> <span class="va">n</span>,</span>
<span>    color <span class="op">=</span> <span class="va">temp_max</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">year</span>, <span class="co"># X-axis: year</span></span>
<span>    y <span class="op">=</span> <span class="va">fit</span>   <span class="co"># Y-axis: GLARMA fitted values</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="co"># Continuous color scale for temperature</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    y <span class="op">=</span> <span class="st">"Population Count"</span>,</span>
<span>    x <span class="op">=</span> <span class="st">"Year"</span>,            </span>
<span>    color <span class="op">=</span> <span class="st">"Temperature"</span> <span class="co"># Legend title</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:adv-06-glarma-plot"></span>
<img src="biostats_files/figure-html/adv-06-glarma-plot-1.png" alt="Observed annual cutthroat trout counts at Mack Creek, Oregon, colored by maximum summer temperature, with fitted values from the first-order GLARMA model overlaid as a line." width="672"><p class="caption">
Figure 22.12: Observed annual cutthroat trout counts at Mack Creek, Oregon, colored by maximum summer temperature, with fitted values from the first-order GLARMA model overlaid as a line.
</p>
</div>

</div>
</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="structural-equation-modeling.html"><span class="header-section-number">21</span> Structural Equation Modeling</a></div>
<div class="next"><a href="basic-terminology.html">Basic Terminology</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#time-series-analysis"><span class="header-section-number">22</span> Time-Series Analysis</a></li>
<li>
<a class="nav-link" href="#pitfall-of-time-series"><span class="header-section-number">22.1</span> Pitfall of Time-Series</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#time-series-anormalies"><span class="header-section-number">22.1.1</span> Time-series anormalies</a></li>
<li><a class="nav-link" href="#temporal-autocorrelation"><span class="header-section-number">22.1.2</span> Temporal autocorrelation</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#basic-models"><span class="header-section-number">22.2</span> Basic Models</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#ar-model"><span class="header-section-number">22.2.1</span> AR Model</a></li>
<li><a class="nav-link" href="#ma-model"><span class="header-section-number">22.2.2</span> MA Model</a></li>
<li><a class="nav-link" href="#arma-model"><span class="header-section-number">22.2.3</span> ARMA Model</a></li>
<li><a class="nav-link" href="#arima-model"><span class="header-section-number">22.2.4</span> ARIMA model</a></li>
<li><a class="nav-link" href="#model-selection"><span class="header-section-number">22.2.5</span> Model selection</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#applied-models"><span class="header-section-number">22.3</span> Applied Models</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#arimax"><span class="header-section-number">22.3.1</span> ARIMAX</a></li>
<li><a class="nav-link" href="#glarma"><span class="header-section-number">22.3.2</span> GLARMA</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/aterui/biostats/blob/master/chapters/adv-06-ts-analysis.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/aterui/biostats/edit/master/chapters/adv-06-ts-analysis.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BIOSTATS</strong>" was written by Akira Terui. It was last built on 2025-12-23.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
