<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 4 Two-Group Comparison | BIOSTATS</title>
<meta name="author" content="Akira Terui">
<meta name="description" content="Data consists of “samples” extracted from the population of interest, but it’s important to acknowledge that these samples are not flawless replicas of the entire population. Given this imperfect...">
<meta name="generator" content="bookdown 0.29 with bs4_book()">
<meta property="og:title" content="Chapter 4 Two-Group Comparison | BIOSTATS">
<meta property="og:type" content="book">
<meta property="og:url" content="https://bookdown.org/janedoe/bookdown-demo/two-group-comparison.html">
<meta property="og:description" content="Data consists of “samples” extracted from the population of interest, but it’s important to acknowledge that these samples are not flawless replicas of the entire population. Given this imperfect...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 4 Two-Group Comparison | BIOSTATS">
<meta name="twitter:description" content="Data consists of “samples” extracted from the population of interest, but it’s important to acknowledge that these samples are not flawless replicas of the entire population. Given this imperfect...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BIOSTATS</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Introduction</a></li>
<li><a class="" href="descriptive-statistics.html"><span class="header-section-number">1</span> Descriptive Statistics</a></li>
<li><a class="" href="sampling.html"><span class="header-section-number">2</span> Sampling</a></li>
<li><a class="" href="probabilistic-view.html"><span class="header-section-number">3</span> Probabilistic View</a></li>
<li><a class="active" href="two-group-comparison.html"><span class="header-section-number">4</span> Two-Group Comparison</a></li>
<li><a class="" href="multiple-group-comparison.html"><span class="header-section-number">5</span> Multiple-Group Comparison</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">6</span> Regression</a></li>
<li><a class="" href="linear-model.html"><span class="header-section-number">7</span> Linear Model</a></li>
<li><a class="" href="generalized-linear-model.html"><span class="header-section-number">8</span> Generalized Linear Model</a></li>
<li><a class="" href="likelihood.html"><span class="header-section-number">9</span> Likelihood</a></li>
<li><a class="" href="model-comparison.html"><span class="header-section-number">10</span> Model Comparison</a></li>
<li><a class="" href="appendix-project.html">Appendix: Project</a></li>
<li><a class="" href="appendix-git-github.html">Appendix: Git &amp; GitHub</a></li>
<li><a class="" href="appendix-data-structure.html">Appendix: Data Structure</a></li>
<li><a class="" href="appendix-tidyverse.html">Appendix: Tidyverse</a></li>
<li><a class="" href="appendix-base-plot.html">Appendix: Base Plot</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/aterui/biostats">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="two-group-comparison" class="section level1" number="4">
<h1>
<span class="header-section-number">4</span> Two-Group Comparison<a class="anchor" aria-label="anchor" href="#two-group-comparison"><i class="fas fa-link"></i></a>
</h1>
<p>Data consists of “samples” extracted from the population of interest, but it’s important to acknowledge that these samples are not flawless replicas of the entire population. Given this imperfect information, how can we effectively investigate and discern the distinction between two populations? In this Chapter, I will introduce one of the most basic statistical tests – “t-test.” The t-test takes the following steps:</p>
<ol style="list-style-type: decimal">
<li>Define a test statistic to signify the difference between groups (t-statistic).</li>
<li>Define a probability distribution of t-statistic under the null hypothesis, i.e., a scenario that we assume no difference between groups.</li>
<li>Estimate the probability of yielding greater or less than the observed test statistic under the null hypothesis.</li>
</ol>
<p><strong>Key words:</strong> t-statistic, null hypothesis, alternative hypothesis, p-value</p>
<div id="explore-data-structure" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Explore Data Structure<a class="anchor" aria-label="anchor" href="#explore-data-structure"><i class="fas fa-link"></i></a>
</h2>
<p>Suppose that we study fish populations of the same species in two lakes (Lake <code>a</code> and <code>b</code>). These lakes are in stark contrast of productivity (Lake <code>b</code> looks more productive), and our interest is the difference in <em>mean</em> body size between the two lakes. We obtained <span class="math inline">\(50\)</span> data points of fish length from each lake (download <a href="https://github.com/aterui/biostats/blob/master/data_raw/data_fish_length.csv">here</a>). Save under <code>data_raw/</code> and use <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> to read data:</p>
<div class="sourceCode" id="cb94"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># call add-in packages everytime you open new R session</span></span>
<span><span class="va">df_fl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data_raw/data_fish_length.csv"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_fl</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 100 × 3
##    lake  length unit 
##    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;
##  1 a       10.8 cm   
##  2 a       13.6 cm   
##  3 a       10.1 cm   
##  4 a       18.6 cm   
##  5 a       14.2 cm   
##  6 a       10.1 cm   
##  7 a       14.7 cm   
##  8 a       15.6 cm   
##  9 a       15   cm   
## 10 a       11.9 cm   
## # ℹ 90 more rows</code></pre>
<p>In this data frame, fish length data from lake <code>a</code> and <code>b</code> are recorded. Confirm this with <code><a href="https://rdrr.io/r/base/unique.html">unique()</a></code> or <code><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct()</a></code> function:</p>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># unique returns unique values as a vector</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">df_fl</span><span class="op">$</span><span class="va">lake</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "a" "b"</code></pre>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># distinct returns unique values as a tibble</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">df_fl</span>, <span class="va">lake</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 2 × 1
##   lake 
##   &lt;chr&gt;
## 1 a    
## 2 b</code></pre>
<p>Visualization provides a powerful tool for summarizing data effectively. By plotting individual data points overlaid with mean values and error bars, we can observe the distribution and patterns within the data, allowing us to identify trends, variations, and potential outliers:</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># group mean and sd</span></span>
<span><span class="va">df_fl_mu</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">lake</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># group operation</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mu_l <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span>, <span class="co"># summarize by mean()</span></span>
<span>            sd_l <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="co"># summarize with sd()</span></span>
<span></span>
<span><span class="co"># plot</span></span>
<span><span class="co"># geom_jitter() plot data points with scatter</span></span>
<span><span class="co"># geom_segment() draw lines</span></span>
<span><span class="co"># geom_point() draw points</span></span>
<span><span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">lake</span>,</span>
<span>             y <span class="op">=</span> <span class="va">length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span>, <span class="co"># scatter width</span></span>
<span>              height <span class="op">=</span> <span class="fl">0</span>, <span class="co"># scatter height (no scatter with zero)</span></span>
<span>              alpha <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span> <span class="co"># transparency of data points</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_fl_mu</span>, <span class="co"># switch data frame</span></span>
<span>               <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">lake</span>,</span>
<span>                   xend <span class="op">=</span> <span class="va">lake</span>,</span>
<span>                   y <span class="op">=</span> <span class="va">mu_l</span> <span class="op">-</span> <span class="va">sd_l</span>,</span>
<span>                   yend <span class="op">=</span> <span class="va">mu_l</span> <span class="op">+</span> <span class="va">sd_l</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df_fl_mu</span>, <span class="co"># switch data frame</span></span>
<span>             <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">lake</span>,</span>
<span>                 y <span class="op">=</span> <span class="va">mu_l</span><span class="op">)</span>,</span>
<span>             size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Lake"</span>, <span class="co"># x label</span></span>
<span>       y <span class="op">=</span> <span class="st">"Fish body length"</span><span class="op">)</span> <span class="co"># y label</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:mean-plot"></span>
<img src="biostats_files/figure-html/mean-plot-1.png" alt="Example of mean and SD plot" width="672"><p class="caption">
Figure 4.1: Example of mean and SD plot
</p>
</div>
<p>Hmm, it is possible that there is a noticeable disparity in body size between Lake <code>a</code> and Lake <code>b</code>. However, how can we ascertain and provide evidence for this claim?</p>
</div>
<div id="test-statistic" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> Test Statistic<a class="anchor" aria-label="anchor" href="#test-statistic"><i class="fas fa-link"></i></a>
</h2>
<div id="t-statistic" class="section level3" number="4.2.1">
<h3>
<span class="header-section-number">4.2.1</span> t-statistic<a class="anchor" aria-label="anchor" href="#t-statistic"><i class="fas fa-link"></i></a>
</h3>
<p>Since our focus is on examining the difference in means, it is logical to estimate the disparity between the sample means in each lake. Let me denote the sample means as <span class="math inline">\(\hat{\mu}_a\)</span> and <span class="math inline">\(\hat{\mu}_b\)</span> for Lake <code>a</code> and Lake <code>b</code>, respectively. We can estimate the difference between the means using the following approach:</p>
<div class="sourceCode" id="cb101"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># take another look at df_fl_mu</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_fl_mu</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   lake   mu_l  sd_l
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 a      13.4  2.92
## 2 b      15.4  3.39</code></pre>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># pull mu_l from tibble as vector</span></span>
<span><span class="va">v_mu</span> <span class="op">&lt;-</span> <span class="va">df_fl_mu</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">mu_l</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># lake a</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 13.35</code></pre>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># lake b</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">v_mu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 15.406</code></pre>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># difference</span></span>
<span><span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">-</span> <span class="va">v_mu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] -2.056</code></pre>
<p>The average fish body size in Lake <code>b</code> is approximately 2 cm larger than that in Lake <code>a</code>. However, it is crucial to recognize that we are still lacking vital information, specifically, the uncertainty associated with this difference. As discussed in Chapter <a href="sampling.html#sampling">2</a>, we must acknowledge that sample means are not flawless representations of the entire population.</p>
<p>Fortunately, we can utilize sample variances to address such uncertainties. The <strong>t-statistic</strong> is a common indicator of the difference of means that takes into consideration the uncertainty associated with sample means.</p>
<p><span class="math display">\[
t = \frac{\hat{\mu_a} - \hat{\mu_b}}{\sqrt{\hat{\sigma}^2_p \left(\frac{1}{N_a} + \frac{1}{N_b}\right)}}
\]</span></p>
<p>where <span class="math inline">\(N_a\)</span> and <span class="math inline">\(N_b\)</span> are sample sizes in Lake <code>a</code> and <code>b</code> (i.e., <span class="math inline">\(N_a = N_b = 50\)</span> in this specific example), and <span class="math inline">\(\hat{\sigma}^2_p\)</span> is the weighted mean of sample variances:</p>
<p><span class="math display">\[
\hat{\sigma}^2_p = \frac{N_a-1}{N_a + N_b - 2}\hat{\sigma}^2_a + \frac{N_b-1}{N_a + N_b - 2}\hat{\sigma}^2_b
\]</span></p>
<p>We can calculate this value in R manually:</p>
<div class="sourceCode" id="cb109"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># group mean, variance, and sample size</span></span>
<span><span class="va">df_t</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">lake</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># group operation</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mu_l <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span>, <span class="co"># summarize by mean()</span></span>
<span>            var_l <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span>, <span class="co"># summarize with sd()</span></span>
<span>            n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="co"># count number of rows per group</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df_t</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   lake   mu_l var_l     n
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 a      13.4  8.52    50
## 2 b      15.4 11.5     50</code></pre>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># pull values as a vector</span></span>
<span><span class="va">v_mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">df_t</span>, <span class="va">mu_l</span><span class="op">)</span></span>
<span><span class="va">v_var</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">df_t</span>, <span class="va">var_l</span><span class="op">)</span></span>
<span><span class="va">v_n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">df_t</span>, <span class="va">n</span><span class="op">)</span></span>
<span></span>
<span><span class="va">var_p</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="op">(</span><span class="va">v_n</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v_n</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="va">v_var</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span></span>
<span>  <span class="op">(</span><span class="op">(</span><span class="va">v_n</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v_n</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="va">v_var</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span></span>
<span><span class="va">t_value</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">v_mu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">-</span> <span class="va">v_mu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var_p</span> <span class="op">*</span> <span class="op">(</span><span class="op">(</span><span class="fl">1</span> <span class="op">/</span> <span class="va">v_n</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">/</span> <span class="va">v_n</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">t_value</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -3.247322</code></pre>
<p>The difference in sample means were -2.06; therefore, t-statistic further emphasizes the distinction between the study lakes. This occurrence can be attributed to the t-statistic formula.</p>
<p>In the denominator, we observe the inclusion of <span class="math inline">\(\hat{\sigma}^2_p\)</span> (estimated pooled variance), as well as the inverses of sample sizes <span class="math inline">\(N_a\)</span> and <span class="math inline">\(N_b\)</span>. Consequently, as <span class="math inline">\(\hat{\sigma}^2_p\)</span> decreases and/or the sample sizes increase, the t-statistic increases. This is a reasonable outcome since a decrease in variance and/or an increase in sample size enhance the certainty of the mean difference.</p>
</div>
<div id="null-hypothesis" class="section level3" number="4.2.2">
<h3>
<span class="header-section-number">4.2.2</span> Null Hypothesis<a class="anchor" aria-label="anchor" href="#null-hypothesis"><i class="fas fa-link"></i></a>
</h3>
<p>The observed t-statistic serves a dual purpose in accounting for both the disparity of means and the accompanying uncertainty. However, the significance of this t-statistic remains unclear.</p>
<p>To address this, the concept of the <strong>Null Hypothesis</strong> is utilized to substantiate the observed t-statistic. The Null Hypothesis, no difference between groups or <span class="math inline">\(\mu_a = \mu_b\)</span>, allows us to draw the probability distribution of the test-statistic. Once we know the probability distribution, we can <strong><em>estimate the probability of observing the given t-statistic by random chance</em></strong> if there were no difference in mean body size between the lakes.</p>
<p>Let’s begin by assuming that there is no difference in the mean body size of fish populations between the lakes, meaning the true difference in means is zero (<span class="math inline">\(\mu_a - \mu_b = 0\)</span>; without hats in this formula!). Under this assumption, we can define the probability distribution of t-statistics, which represents how t-statistics are distributed across a range of possible values.</p>
<p>This probability distribution is known as the Student’s t-distribution and is characterized by three parameters: the mean, the variance, and the degrees of freedom (d.f.). Considering that we are evaluating the difference in body size as the test statistic, the mean (of the difference) is assumed to be zero. The variance is estimated using <span class="math inline">\(\hat{\sigma}^2_p\)</span>, and the degrees of freedom are determined by <span class="math inline">\(N_a + N_b - 2\)</span> (where d.f. can be considered as a measure related to the sample size<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Discussing the concept of degrees of freedom in depth would require a more comprehensive explanation, so I will refer to it here as a quantity relevant to the sample size.&lt;/p&gt;"><sup>2</sup></a>).</p>
<p>R has a function to draw the Student’s t-distribution; let’s try that out:</p>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># produce 500 values from -5 to 5 with equal interval</span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">5</span>, <span class="fl">5</span>, length <span class="op">=</span> <span class="fl">500</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># probability density of t-statistics with df = sum(v_n) - 2</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">dt</a></span><span class="op">(</span><span class="va">x</span>, df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v_n</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># draw figure</span></span>
<span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>,</span>
<span>             y <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Probability density"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"t-statistic"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:student-t"></span>
<img src="biostats_files/figure-html/student-t-1.png" alt="Distribution of t-statistics under null hypothesis. The probability density in a distribution determines the likelihood of observing a particular t-statistic. Higher probability density indicates a greater likelihood of the t-statistic occurring." width="672"><p class="caption">
Figure 4.2: Distribution of t-statistics under null hypothesis. The probability density in a distribution determines the likelihood of observing a particular t-statistic. Higher probability density indicates a greater likelihood of the t-statistic occurring.
</p>
</div>
<p>The probability density in a distribution (Figure <a href="two-group-comparison.html#fig:student-t">4.2</a>) determines the likelihood of observing a particular t-statistic. Higher probability density indicates a greater likelihood of the t-statistic occurring. Compare the observed t-statistic against this null distribution:</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># draw entire range</span></span>
<span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>,</span>
<span>             y <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">t_value</span>,</span>
<span>             color <span class="op">=</span> <span class="st">"salmon"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># t_value is the observed t_value</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">t_value</span><span class="op">)</span>,</span>
<span>             color <span class="op">=</span> <span class="st">"salmon"</span><span class="op">)</span> <span class="op">+</span> <span class="co"># t_value is the observed t_value</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Probability density"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"t-statistic"</span><span class="op">)</span> </span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:student-t-obs"></span>
<img src="biostats_files/figure-html/student-t-obs-1.png" alt="Observed t-statistic in comparison to the null distrubution" width="672"><p class="caption">
Figure 4.3: Observed t-statistic in comparison to the null distrubution
</p>
</div>
<p>In a probability distribution, the area under the curve corresponds to the probability. Notably, <strong>the area under the curve that falls below or above the observed t-statistic (indicated by vertical red lines) is very small (Figure</strong> <a href="two-group-comparison.html#fig:student-t-obs">4.3</a><strong>)</strong>, meaning that the observed difference in body size is very unlikely to occur under the null hypothesis (no difference in true means).</p>
<p>The function <code><a href="https://rdrr.io/r/stats/TDist.html">pt()</a></code> allows us to calculate the area under the curve:</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># calculate area under the curve from -infinity to t_value</span></span>
<span><span class="va">pr_below</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span>q <span class="op">=</span> <span class="va">t_value</span>, df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v_n</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># calculate area under the curve from abs(t_value) to infinity</span></span>
<span><span class="va">pr_above</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">t_value</span><span class="op">)</span>, df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v_n</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<p>The <strong>p-value,</strong> i.e., <em>the probability of observing t-statistics</em> less than ( <code>pr_below</code>) or greater than (<code>pr_above</code>) the observed t-statistic under the null hypothesis, can be estimated as the sum of <code>pr_below</code> and <code>pr_above</code>.</p>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># p_value</span></span>
<span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="va">pr_below</span> <span class="op">+</span> <span class="va">pr_above</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">p_value</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.001595529</code></pre>
</div>
<div id="interpretation" class="section level3" number="4.2.3">
<h3>
<span class="header-section-number">4.2.3</span> Interpretation<a class="anchor" aria-label="anchor" href="#interpretation"><i class="fas fa-link"></i></a>
</h3>
<p>The above exercise is called <strong>t-test</strong> – perhaps, the most well-known hypothesis testing. To explain the interpretation of the results, let me use the following notations. <span class="math inline">\(t_{obs}\)</span>, the observed t-statistic; <span class="math inline">\(t_0\)</span>, possible t-statistics under the null hypothesis; <span class="math inline">\(\Pr(\cdot)\)</span>, the probability of “<span class="math inline">\(\cdot\)</span>” occurs – for example, <span class="math inline">\(\Pr(x &gt; 2)\)</span> means that the probability of <span class="math inline">\(x\)</span> exceeding <span class="math inline">\(2\)</span>.</p>
<p>We first calculated the observed t-statistic <span class="math inline">\(t_{obs}\)</span> using the data of fish body size, which was -3.25. Then, we calculated p-value, i.e., <span class="math inline">\(\Pr(t_0 &lt; t_{obs}) + \Pr(t_0 &gt; t_{obs})\)</span> under the null hypothesis of <span class="math inline">\(\mu_a = \mu_b\)</span>. We found p-value was very low, meaning that the observed t-statistic is very unlikely to occur if <span class="math inline">\(\mu_a = \mu_b\)</span> is the truth. Therefore, it is logical to conclude that the <strong>Alternative Hypothesis</strong> <span class="math inline">\(\mu_a \ne \mu_b\)</span> is very likely.</p>
<p>The same logic is used in many statistical analyses – define the null hypothesis, and estimate the probability of observing a given value under the null hypothesis. It is tricky, but I find this genius: we can substantiate the observation(s) objectively that are otherwise a subjective claim!</p>
<p>However, it is crucial to recognize that, <strong>even if we found the observed t-statistic that results in very high p-value (i.e., very common under the null hypothesis), finding such a result does NOT support the null hypothesis – we just can’t reject it.</strong></p>
</div>
</div>
<div id="t-test-in-r" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> t-test in R<a class="anchor" aria-label="anchor" href="#t-test-in-r"><i class="fas fa-link"></i></a>
</h2>
<div id="t-test-with-equal-variance" class="section level3" number="4.3.1">
<h3>
<span class="header-section-number">4.3.1</span> t-test with equal variance<a class="anchor" aria-label="anchor" href="#t-test-with-equal-variance"><i class="fas fa-link"></i></a>
</h3>
<p>In R, this t-test can be performed with <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>. Let me examine if the function gives us identical results:</p>
<div class="sourceCode" id="cb118"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">lake</span> <span class="op">==</span> <span class="st">"a"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>  <span class="co"># subset lake a</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span></span>
<span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="va">df_fl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">lake</span> <span class="op">==</span> <span class="st">"b"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="co"># subset lake b</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">length</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  x and y
## t = -3.2473, df = 98, p-value = 0.001596
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.3124399 -0.7995601
## sample estimates:
## mean of x mean of y 
##    13.350    15.406</code></pre>
<p>The reported t-statistic <code>t = -3.2473</code>, the p-value <code>p-value = 0.001596</code>, and the degrees of freedom all agreed (<code>df = 98</code>) with what we have estimated manually. Importantly, this t-test assumes relative similarity of variance between groups.</p>
</div>
<div id="t-test-with-unequal-variance" class="section level3" number="4.3.2">
<h3>
<span class="header-section-number">4.3.2</span> t-test with unequal variance<a class="anchor" aria-label="anchor" href="#t-test-with-unequal-variance"><i class="fas fa-link"></i></a>
</h3>
<p>The relative similarity of variance between groups could be an unrealistic assumption. Luckily, there is a variant of t-test “Welch’s t-test,” in which we assume unequal variance between groups. The implementation is easy – set <code>var.equal = FALSE</code> in <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code>:</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, var.equal <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -3.2473, df = 95.846, p-value = 0.001606
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.3127929 -0.7992071
## sample estimates:
## mean of x mean of y 
##    13.350    15.406</code></pre>
<p>In Welch’s t-test, t-statistics are defined differently to account for unequal variance between groups<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;When &lt;span class="math inline"&gt;\(\hat{\sigma}^2_a \approx \hat{\sigma}_b^2\)&lt;/span&gt;, the t-statistic for Welch’s t-test is reduced to the original t-statistic.&lt;/p&gt;'><sup>3</sup></a>:</p>
<p><span class="math display">\[
t = \frac{\hat{\mu_a} - \hat{\mu_b}}{\sqrt{\left(\frac{\hat{\sigma}^2_a}{N_a} + \frac{\hat{\sigma}^2_b}{N_b}\right)}}
\]</span></p>
<p>This t-statistic is known to follow the Student’s t-distribution with the degrees of freedom:</p>
<p><span class="math display">\[
d.f. = \frac{\frac{\hat{\sigma}^2_a}{N_a} + \frac{\hat{\sigma}^2_b}{N_b}}{\frac{(\hat{\sigma}^2_a / N_a)^2}{N_a - 1} + \frac{(\hat{\sigma}^2_b/N_b)^2}{N_b-1}}
\]</span></p>
<p>Therefore, the reported values of t-statistic and d.f. are different from what we estimated. The Welch’s t-test covers the cases for equal variances; therefore, by default, we use the Welch’s test.</p>
</div>
</div>
<div id="laboratory-3" class="section level2" number="4.4">
<h2>
<span class="header-section-number">4.4</span> Laboratory<a class="anchor" aria-label="anchor" href="#laboratory-3"><i class="fas fa-link"></i></a>
</h2>
<div id="welchs-t-test" class="section level3" number="4.4.1">
<h3>
<span class="header-section-number">4.4.1</span> Welch’s t-test<a class="anchor" aria-label="anchor" href="#welchs-t-test"><i class="fas fa-link"></i></a>
</h3>
<p>Reproduce the results of <code>t.test(x, y, var.equal = FALSE)</code> without using this function (report t-statistic, degrees of freedom, and p-value).</p>
</div>
<div id="difference-and-uncertainty" class="section level3" number="4.4.2">
<h3>
<span class="header-section-number">4.4.2</span> Difference and Uncertainty<a class="anchor" aria-label="anchor" href="#difference-and-uncertainty"><i class="fas fa-link"></i></a>
</h3>
<p>We have four vectors - <code>a1</code> and <code>a2</code> &amp; <code>b1</code> and <code>b2</code>.</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">a1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">13.9</span>, <span class="fl">14.9</span> ,<span class="fl">13.4</span>, <span class="fl">14.3</span>, <span class="fl">11.8</span>, <span class="fl">13.9</span>, <span class="fl">14.5</span>, <span class="fl">15.1</span>, <span class="fl">13.3</span>, <span class="fl">13.9</span><span class="op">)</span></span>
<span><span class="va">a2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">17.4</span>, <span class="fl">17.3</span>, <span class="fl">20.1</span>, <span class="fl">17.2</span>, <span class="fl">18.4</span>, <span class="fl">19.6</span>, <span class="fl">16.8</span>, <span class="fl">18.7</span>, <span class="fl">17.8</span>, <span class="fl">18.9</span><span class="op">)</span></span>
<span></span>
<span><span class="va">b1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10.9</span>, <span class="fl">20.3</span>, <span class="fl">9.6</span>, <span class="fl">8.3</span>, <span class="fl">14.5</span>, <span class="fl">12.3</span>, <span class="fl">14.5</span>, <span class="fl">16.7</span>, <span class="fl">9.3</span>, <span class="fl">22.0</span><span class="op">)</span></span>
<span><span class="va">b2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">26.9</span>, <span class="fl">12.9</span>, <span class="fl">11.1</span>, <span class="fl">16.7</span>, <span class="fl">20.0</span>, <span class="fl">20.9</span>, <span class="fl">16.6</span>, <span class="fl">15.4</span>, <span class="fl">16.2</span>, <span class="fl">16.2</span><span class="op">)</span></span></code></pre></div>
<p>Perform the following analysis:</p>
<ol style="list-style-type: decimal">
<li>Estimate sample means and SDs for each vector. To do so, create a <code><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble()</a></code> object with <code>group</code> (consist of characters <code>a1</code>, <code>a2</code>, <code>b1</code>, <code>b2</code>) and <code>value</code> columns (consist of values above). Then use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code> functions to estimate means and SDs for each <code>group</code>.</li>
<li>Estimate t-statistics for each pair of vectors (<code>a1</code> vs. <code>a2</code> and <code>b1</code> vs. <code>b2</code>).</li>
<li>Perform Welch’s t-test for each pair and compare results.</li>
</ol>
</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="probabilistic-view.html"><span class="header-section-number">3</span> Probabilistic View</a></div>
<div class="next"><a href="multiple-group-comparison.html"><span class="header-section-number">5</span> Multiple-Group Comparison</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#two-group-comparison"><span class="header-section-number">4</span> Two-Group Comparison</a></li>
<li><a class="nav-link" href="#explore-data-structure"><span class="header-section-number">4.1</span> Explore Data Structure</a></li>
<li>
<a class="nav-link" href="#test-statistic"><span class="header-section-number">4.2</span> Test Statistic</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#t-statistic"><span class="header-section-number">4.2.1</span> t-statistic</a></li>
<li><a class="nav-link" href="#null-hypothesis"><span class="header-section-number">4.2.2</span> Null Hypothesis</a></li>
<li><a class="nav-link" href="#interpretation"><span class="header-section-number">4.2.3</span> Interpretation</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#t-test-in-r"><span class="header-section-number">4.3</span> t-test in R</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#t-test-with-equal-variance"><span class="header-section-number">4.3.1</span> t-test with equal variance</a></li>
<li><a class="nav-link" href="#t-test-with-unequal-variance"><span class="header-section-number">4.3.2</span> t-test with unequal variance</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#laboratory-3"><span class="header-section-number">4.4</span> Laboratory</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#welchs-t-test"><span class="header-section-number">4.4.1</span> Welch’s t-test</a></li>
<li><a class="nav-link" href="#difference-and-uncertainty"><span class="header-section-number">4.4.2</span> Difference and Uncertainty</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/aterui/biostats/blob/master/chapters/04-two-group.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/aterui/biostats/edit/master/chapters/04-two-group.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BIOSTATS</strong>" was written by Akira Terui. It was last built on 2023-07-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
