<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 19 Unconstrained Ordination | BIOSTATS</title>
<meta name="author" content="Akira Terui">
<meta name="description" content="So far, our modeling exercises have focused on univariate analyses, where we model a single response variable using one or more predictors. In practice, biological data are often multivariate,...">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="Chapter 19 Unconstrained Ordination | BIOSTATS">
<meta property="og:type" content="book">
<meta property="og:description" content="So far, our modeling exercises have focused on univariate analyses, where we model a single response variable using one or more predictors. In practice, biological data are often multivariate,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 19 Unconstrained Ordination | BIOSTATS">
<meta name="twitter:description" content="So far, our modeling exercises have focused on univariate analyses, where we model a single response variable using one or more predictors. In practice, biological data are often multivariate,...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-QZSNHVQQNV"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-QZSNHVQQNV');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BIOSTATS</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Introduction</a></li>
<li class="book-part">Getting Started</li>
<li><a class="" href="what-is-r-and-r-studio.html"><span class="header-section-number">1</span> What is R and R studio?</a></li>
<li><a class="" href="installing-r-and-rstudio.html"><span class="header-section-number">2</span> Installing R and RStudio</a></li>
<li><a class="" href="r-project.html"><span class="header-section-number">3</span> R Project</a></li>
<li class="book-part">R Basics</li>
<li><a class="" href="data-structure.html"><span class="header-section-number">4</span> Data Structure</a></li>
<li><a class="" href="data-manipulation.html"><span class="header-section-number">5</span> Data Manipulation</a></li>
<li><a class="" href="visualization.html"><span class="header-section-number">6</span> Visualization</a></li>
<li class="book-part">Basic Statistics</li>
<li><a class="" href="descriptive-statistics.html"><span class="header-section-number">7</span> Descriptive Statistics</a></li>
<li><a class="" href="sampling.html"><span class="header-section-number">8</span> Sampling</a></li>
<li><a class="" href="probabilistic-view.html"><span class="header-section-number">9</span> Probabilistic View</a></li>
<li><a class="" href="two-group-comparison.html"><span class="header-section-number">10</span> Two-Group Comparison</a></li>
<li><a class="" href="multiple-group-comparison.html"><span class="header-section-number">11</span> Multiple-Group Comparison</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">12</span> Regression</a></li>
<li><a class="" href="linear-model.html"><span class="header-section-number">13</span> Linear Model</a></li>
<li><a class="" href="generalized-linear-model.html"><span class="header-section-number">14</span> Generalized Linear Model</a></li>
<li><a class="" href="likelihood.html"><span class="header-section-number">15</span> Likelihood</a></li>
<li><a class="" href="model-comparison.html"><span class="header-section-number">16</span> Model Comparison</a></li>
<li class="book-part">Applied Statistics</li>
<li><a class="" href="generalized-linear-mixed-effect-model.html"><span class="header-section-number">17</span> Generalized Linear Mixed Effect Model</a></li>
<li><a class="" href="generalized-additive-model.html"><span class="header-section-number">18</span> Generalized Additive Model</a></li>
<li><a class="active" href="unconstrained-ordination.html"><span class="header-section-number">19</span> Unconstrained Ordination</a></li>
<li><a class="" href="constrained-ordination.html"><span class="header-section-number">20</span> Constrained Ordination</a></li>
<li><a class="" href="structural-equation-modeling.html"><span class="header-section-number">21</span> Structural Equation Modeling</a></li>
<li><a class="" href="time-series-analaysis.html"><span class="header-section-number">22</span> Time-Series Analaysis</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="basic-terminology.html"><span class="header-section-number">23</span> Basic Terminology</a></li>
<li><a class="" href="git-github.html">Git &amp; GitHub</a></li>
<li><a class="" href="base-plot.html">Base Plot</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/aterui/biostats">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="unconstrained-ordination" class="section level1" number="19">
<h1>
<span class="header-section-number">19</span> Unconstrained Ordination<a class="anchor" aria-label="anchor" href="#unconstrained-ordination"><i class="fas fa-link"></i></a>
</h1>
<p>So far, our modeling exercises have focused on univariate analyses, where we model a single response variable using one or more predictors. In practice, biological data are often multivariate, with multiple variables describing the same system. It is useful to reduce many correlated variables into a smaller number of axes that capture the main patterns of variation. In this chapter, we will learn methods that allow us to summarize multivariate data into fewer dimensions.</p>
<p>Learning Objectives:</p>
<ul>
<li><p>Understand and apply unconstrained ordination methods such as PCA and NMDS to summarize and visualize multivariate data.</p></li>
<li><p>Interpret ordination outputs, including principal component axes, NMDS coordinates, and stress values.</p></li>
<li><p>Compare and select appropriate ordination methods (PCA, NMDS, PCoA, CA, MCA) based on data type, distribution, and research questions.</p></li>
</ul>
<div class="sourceCode" id="cb516"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>,</span>
<span>               <span class="va">GGally</span>,</span>
<span>               <span class="va">vegan</span><span class="op">)</span></span></code></pre></div>
<div id="methods-for-unconstrained-ordination" class="section level2" number="19.1">
<h2>
<span class="header-section-number">19.1</span> Methods for Unconstrained Ordination<a class="anchor" aria-label="anchor" href="#methods-for-unconstrained-ordination"><i class="fas fa-link"></i></a>
</h2>
<p>We will explore <strong>unconstrained ordination methods</strong> for summarizing multivariate data. These methods differ in their assumptions, flexibility, and how interpretable the axes are, and the choice of method depends on the goals of your analysis. Here, we will focus on two extreme cases—<strong>PCA</strong> and <strong>NMDS</strong>—and demonstrate their application with examples. We will conclude by briefly introducing other ordination options, highlighting their potential uses for future analyses.</p>
<div id="pca" class="section level3" number="19.1.1">
<h3>
<span class="header-section-number">19.1.1</span> PCA<a class="anchor" aria-label="anchor" href="#pca"><i class="fas fa-link"></i></a>
</h3>
<div id="flower-shape" class="section level4 unnumbered">
<h4>Flower “shape”<a class="anchor" aria-label="anchor" href="#flower-shape"><i class="fas fa-link"></i></a>
</h4>
<p>We will use the iris dataset for this exercise. This dataset contains multiple measurements of each flower from the same individual, and <a href="https://www.anscenter.com.au/post/making-a-machine-learning-model-to-classify-iris-flowers">these measurements</a> (length and width dimensions of sepal and petal) are highly correlated, collectively capturing the overall “shape” of the flower.</p>
<p>Before we begin, we will clean the data to simplify variable names and ensure consistency, since mixed cases and formatting can be cumbersome.</p>
<div class="sourceCode" id="cb517"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Convert the built-in iris dataset into a tibble and clean column names</span></span>
<span><span class="va">df_iris</span> <span class="op">&lt;-</span> <span class="va">iris</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>               <span class="co"># Convert from data.frame to tibble for tidyverse-friendly operations</span></span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span>        <span class="co"># Standardize column names: lowercase, replace spaces/special characters</span></span></code></pre></div>
<p>Next, we explore the relationships among the numeric measurements in the iris dataset. Since the variables are likely correlated, we use a scatterplot matrix to visualize pairwise relationships and see how the three species differ. The <code>ggpairs()</code> function from the <code>GGally</code> package makes this easy.</p>
<div class="sourceCode" id="cb518"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_iris</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">ggpairs</span><span class="op">(</span></span>
<span>    progress <span class="op">=</span> <span class="cn">FALSE</span>, <span class="co"># Disable progress bar during plotting</span></span>
<span>    columns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sepal_length"</span>, <span class="co"># Select the four numeric columns to include</span></span>
<span>                <span class="st">"sepal_width"</span>,</span>
<span>                <span class="st">"petal_length"</span>,</span>
<span>                <span class="st">"petal_width"</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>      color <span class="op">=</span> <span class="va">species</span>, <span class="co"># Color points by species</span></span>
<span>      alpha <span class="op">=</span> <span class="fl">0.5</span> <span class="co"># Make points semi-transparent for better visibility</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># Use a clean theme for better readability</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:iris-multiplot"></span>
<img src="biostats_files/figure-html/iris-multiplot-1.png" alt="Pairwise scatterplots of the four iris traits (sepal length, sepal width, petal length, and petal width) colored by species. The plots show relationships among traits, highlight species-specific trait distributions, and reveal correlations or patterns in the data." width="672"><p class="caption">
Figure 19.1: Pairwise scatterplots of the four iris traits (sepal length, sepal width, petal length, and petal width) colored by species. The plots show relationships among traits, highlight species-specific trait distributions, and reveal correlations or patterns in the data.
</p>
</div>
<p>With few exceptions, most variable combinations are correlated with each other, suggesting that they may contain overlapping information that can be summarized along fewer axes.</p>
<p>When variables are approximately normally distributed and show substantial correlations, Principal Component Analysis (PCA) provides an effective way to summarize multiple variables into a smaller set of axes. PCA identifies orthogonal axes based on the variance–covariance structure of the variables, under the assumption of multivariate normality.</p>
<p>Without going into too much detail, PCA can be performed in R using the <code><a href="https://rdrr.io/r/stats/prcomp.html">prcomp()</a></code> function. For simplicity, the example below focuses on two variables (<code>petal_length</code> and <code>petal_width</code>). An important point when using <code><a href="https://rdrr.io/r/stats/prcomp.html">prcomp()</a></code> is to almost always set <code>scale = TRUE</code> explicitly, since PCA is not intended to summarize variables measured on different scales or with different variances.</p>
<div class="sourceCode" id="cb519"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Extract only the petal measurements from the iris dataset</span></span>
<span><span class="va">df_petal</span> <span class="op">&lt;-</span> <span class="va">df_iris</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="co"># Select columns whose names start with "petal_" (petal length and petal width)</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"petal_"</span><span class="op">)</span><span class="op">)</span> </span>
<span></span>
<span><span class="co"># Perform Principal Component Analysis (PCA) on the selected petal data</span></span>
<span><span class="va">obj_pca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/prcomp.html">prcomp</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="va">df_petal</span>,    <span class="co"># Input data for PCA</span></span>
<span>  center <span class="op">=</span> <span class="cn">TRUE</span>,   <span class="co"># Subtract the mean of each column so variables are centered at 0</span></span>
<span>  scale <span class="op">=</span> <span class="cn">TRUE</span>     <span class="co"># Divide by the standard deviation of each column so variables have unit variance</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># obj_pca now contains:</span></span>
<span><span class="co"># - obj_pca$x        : PCA scores (coordinates of each sample in PC space)</span></span>
<span><span class="co"># - obj_pca$rotation : Eigenvectors (directions of principal components)</span></span>
<span><span class="co"># - obj_pca$sdev     : Standard deviations of the principal components (square = variance explained)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">obj_pca</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Standard deviations (1, .., p=2):
## [1] 1.4010230 0.1927033
## 
## Rotation (n x k) = (2 x 2):
##                    PC1        PC2
## petal_length 0.7071068 -0.7071068
## petal_width  0.7071068  0.7071068</code></pre>
<p>The standard deviations of the principal components (PCs) indicate how much the data varies along each axis. In this case, PC1 has a standard deviation of 1.401, much higher than PC2’s 0.193, meaning that most of the variation in petal length and width occurs along PC1. Squaring these values gives the eigenvalues, which quantify the variance captured by each component.</p>
<p>The proportion of variance shows that PC1 explains approximately 98% of the total variance, while PC2 accounts for only about 2%. The cumulative proportion confirms that together they capture 100% of the variation. This means PC1 effectively summarizes almost all the information in the dataset, and PC2 adds very little new insight.</p>
<p>Visualization helps illustrate how PCA summarizes the variables. As shown in this figure, the principal component axes identified by <code><a href="https://rdrr.io/r/stats/prcomp.html">prcomp()</a></code> represent orthogonal dimensions of the relationships, with the first axis capturing the largest variance (eigenvalue) and therefore most of the information from the original variables.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:eigenvector-plot"></span>
<img src="biostats_files/figure-html/eigenvector-plot-1.png" alt="Scatter plot of scaled petal length and width for three Iris species (subtract the means, then divide by SDs). Points represent individual flowers and are colored by species. Red lines represent the contribution of each principal component to the variation in petal length and width. Black arrows indicate the directions of the principal components for visual reference. Text labels at the arrow tips denote the corresponding principal component." width="672"><p class="caption">
Figure 19.2: Scatter plot of scaled petal length and width for three Iris species (subtract the means, then divide by SDs). Points represent individual flowers and are colored by species. Red lines represent the contribution of each principal component to the variation in petal length and width. Black arrows indicate the directions of the principal components for visual reference. Text labels at the arrow tips denote the corresponding principal component.
</p>
</div>
</div>
<div id="extracting-pc-values" class="section level4 unnumbered">
<h4>Extracting PC values<a class="anchor" aria-label="anchor" href="#extracting-pc-values"><i class="fas fa-link"></i></a>
</h4>
<p>Once PCA is performed, you may wonder how the original data points are positioned in the PCA space. The <code><a href="https://rdrr.io/r/stats/prcomp.html">prcomp()</a></code> function returns the principal component (PC) scores for each data point, allowing you to relate these values back to the original data. These coordinates are stored in the <code>$x</code> element of the <code>prcomp</code> object, where the first and second columns correspond to PC1 and PC2 (and additional columns correspond to as many axes as the number of variables included in the PCA).</p>
<p>Since <code><a href="https://rdrr.io/r/stats/prcomp.html">prcomp()</a></code> preserves the order of the original data, you can safely combine the <code>$x</code> scores with the original dataset using <code><a href="https://dplyr.tidyverse.org/reference/bind_cols.html">bind_cols()</a></code>. Just be careful not to alter the row order, as this would misalign the PC scores with the corresponding original observations.</p>
<div class="sourceCode" id="cb521"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Combine the original iris dataset with PCA scores</span></span>
<span><span class="va">df_pca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_cols.html">bind_cols</a></span><span class="op">(</span></span>
<span>  <span class="va">df_iris</span>,              <span class="co"># Original dataset (all columns: species, sepal, and petal measurements)</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">obj_pca</span><span class="op">$</span><span class="va">x</span><span class="op">)</span>  <span class="co"># PCA scores for each observation (PC1, PC2, ...)</span></span>
<span><span class="op">)</span></span></code></pre></div>
<p>In this example, we will focus on PC1, since PC2 contributes very little information about petal shape. Converting PC1 into an ordinal code allows us to compare how its values differ among species.</p>
<div class="sourceCode" id="cb522"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df_pca</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">species</span>,   <span class="co"># x-axis: categorical variable (species)</span></span>
<span>    y <span class="op">=</span> <span class="va">PC1</span>,       <span class="co"># y-axis: PCA scores for the first principal component</span></span>
<span>    color <span class="op">=</span> <span class="va">species</span> <span class="co"># Color the boxplots by species</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Species"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Petal shape (PC1)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="biostats_files/figure-html/pc-plot-1.png" width="672" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="nmds" class="section level3" number="19.1.2">
<h3>
<span class="header-section-number">19.1.2</span> NMDS<a class="anchor" aria-label="anchor" href="#nmds"><i class="fas fa-link"></i></a>
</h3>
<div id="dune-community-data" class="section level4 unnumbered">
<h4>Dune community data<a class="anchor" aria-label="anchor" href="#dune-community-data"><i class="fas fa-link"></i></a>
</h4>
<p>Having explored PCA using the iris dataset, we saw how linear ordination can summarize variation in continuous, roughly normally distributed traits. However, many biological datasets do not meet these assumptions. For example, species abundances are often zero-inflated, skewed, or otherwise non-normal.</p>
<p>Non-metric ordination methods, such as Non-metric Multidimensional Scaling (NMDS), overcome the limitations of linear ordination by operating directly on a matrix of pairwise dissimilarities between sites (or other observational units). In this example, we will use the <code>dune</code> dataset, Vegetation and Environment in Dutch Dune Meadows, to illustrate the strengths and applications of NMDS.</p>
<div class="sourceCode" id="cb523"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## call sample data from vegan package</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">dune</span><span class="op">)</span></span></code></pre></div>
<p>The <code>dune</code> dataset contains a species abundance matrix with 20 rows and 30 columns. Each row represents a unique sampling site in the dune meadows, and each column corresponds to a plant species. The values indicate the abundance of each species at each site, typically measured as counts of individuals or percent cover. This multivariate structure makes the dataset well suited for ordination methods, as each site can be characterized by its overall species composition.</p>
<div class="sourceCode" id="cb524"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## the first 3 species</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dune</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Achimill Agrostol Airaprae
## 1        1        0        0
## 2        3        0        0
## 3        0        4        0
## 4        0        8        0
## 5        2        0        0
## 6        2        0        0</code></pre>
<p>Visualization reveals pronounced non-normality and non-linearity in the data. As an example, we plot the first three species. The distributions are strongly right-skewed, clearly deviating from a normal distribution.</p>
<div class="sourceCode" id="cb526"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Take the 'dune' dataset from vegan</span></span>
<span><span class="va">dune</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>         <span class="co"># Convert 'dune' from matrix/data frame to tibble for tidyverse compatibility</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>         <span class="co"># Select the first three species (columns) for visualization</span></span>
<span>  <span class="fu">ggpairs</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>             <span class="co"># Create a pairwise scatterplot matrix (plots all pairwise relationships)</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span>              <span class="co"># Apply a clean, minimal theme with a white background</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:dune-plot"></span>
<img src="biostats_files/figure-html/dune-plot-1.png" alt="Pairwise scatterplots of the first three plant species in the Dutch dune meadows dataset (dune). The plots visualize relationships among species abundances across sites, highlighting correlations, patterns, and potential non-normality in the data." width="672"><p class="caption">
Figure 19.3: Pairwise scatterplots of the first three plant species in the Dutch dune meadows dataset (dune). The plots visualize relationships among species abundances across sites, highlighting correlations, patterns, and potential non-normality in the data.
</p>
</div>
<p>In PCA, when representing the data using a reduced number of axes, the method identifies orthogonal dimensions that capture the main “cloud” of variation in the data. However, if the underlying relationships are non-linear, this linear approach may fail to capture important patterns.</p>
<p>In contrast, NMDS aims to find a set of axes that best preserve the ranked dissimilarities between sites. The first step in NMDS is to convert the community matrix into a distance matrix. This produces an N × N matrix (where N is the number of sites), with each cell representing the dissimilarity in species composition between a pair of sites. The <code>vegdist()</code> function from the <code>vegan</code> package provides a straightforward way to compute a distance (or dissimilarity) matrix from a community or multivariate dataset.</p>
<div class="sourceCode" id="cb527"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Compute pairwise dissimilarities between sites using Bray-Curtis distance</span></span>
<span><span class="va">m_bray</span> <span class="op">&lt;-</span> <span class="fu">vegdist</span><span class="op">(</span><span class="va">dune</span>,       <span class="co"># Input community matrix (sites × species)</span></span>
<span>                  method <span class="op">=</span> <span class="st">"bray"</span><span class="op">)</span>  <span class="co"># Use Bray-Curtis dissimilarity, commonly used in ecology</span></span>
<span></span>
<span><span class="co"># Inspect the first 3 rows and columns of the distance matrix</span></span>
<span><span class="co"># Convert 'm_bray' (a dist object) to a standard matrix for easy subsetting</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.matrix.html">data.matrix</a></span><span class="op">(</span><span class="va">m_bray</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span>  <span class="co"># Show pairwise dissimilarities among the first 3 sites</span></span></code></pre></div>
<pre><code>##           1         2         3
## 1 0.0000000 0.4666667 0.4482759
## 2 0.4666667 0.0000000 0.3414634
## 3 0.4482759 0.3414634 0.0000000</code></pre>
<p>Here, we used the “Bray-Curtis” distance (<code>method = "bray</code>), which is a widely used measure of dissimilarity in ecology that quantifies differences in species composition between two sites based on abundances. It ranges from 0 (identical composition) to 1 (completely different composition). Importantly, Bray-Curtis ignores joint absences—species absent from both sites do not contribute to dissimilarity—making it well-suited for ecological community data.</p>
<p>Other distance or dissimilarity measures are also available, depending on the type of data and the ecological question. Examples include Jaccard, Euclidean, Manhattan, and many others. A full list of metrics supported by <code>vegdist()</code> in the vegan package can be found <a href="https://cran.r-project.org/web/packages/vegan/vegan.pdf#page=17">here</a>.</p>
<p>Next, we will use the <code>metaMDS()</code> function from the <code>vegan</code> package to perform NMDS on this distance matrix.</p>
<div class="sourceCode" id="cb529"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Perform Non-metric Multidimensional Scaling (NMDS) </span></span>
<span><span class="va">obj_nmds</span> <span class="op">&lt;-</span> <span class="fu">metaMDS</span><span class="op">(</span></span>
<span>  <span class="va">m_bray</span>,   <span class="co"># Input distance matrix (e.g., Bray-Curtis dissimilarities between sites)</span></span>
<span>  k <span class="op">=</span> <span class="fl">2</span>     <span class="co"># Number of dimensions (axes) to represent in the NMDS solution</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>## Run 0 stress 0.1192678 
## Run 1 stress 0.1183186 
## ... New best solution
## ... Procrustes: rmse 0.02027061  max resid 0.06496334 
## Run 2 stress 0.1886532 
## Run 3 stress 0.1886532 
## Run 4 stress 0.1192678 
## Run 5 stress 0.1183186 
## ... Procrustes: rmse 4.650431e-06  max resid 1.53307e-05 
## ... Similar to previous best
## Run 6 stress 0.1192678 
## Run 7 stress 0.1812933 
## Run 8 stress 0.1183186 
## ... Procrustes: rmse 1.144619e-06  max resid 3.080589e-06 
## ... Similar to previous best
## Run 9 stress 0.1192679 
## Run 10 stress 0.1192679 
## Run 11 stress 0.2035424 
## Run 12 stress 0.1192678 
## Run 13 stress 0.2075713 
## Run 14 stress 0.1192678 
## Run 15 stress 0.1900906 
## Run 16 stress 0.1183186 
## ... Procrustes: rmse 1.098301e-05  max resid 3.764092e-05 
## ... Similar to previous best
## Run 17 stress 0.1192678 
## Run 18 stress 0.1192678 
## Run 19 stress 0.1192678 
## Run 20 stress 0.1183186 
## ... Procrustes: rmse 1.983547e-05  max resid 6.214347e-05 
## ... Similar to previous best
## *** Best solution repeated 4 times</code></pre>
<p>The <code>metaMDS()</code> function positions sites in a user-specified k-dimensional space (<code>k = 2</code>) so that the <strong>ranked distances</strong> (not observed distances!) in this reduced space closely match the original dissimilarities. It achieves this through an iterative optimization algorithm.</p>
<p>The resulting NMDS object contains several important pieces of information. It includes the coordinates of sites in NMDS space, which can be used for visualization or further analysis. It also reports a stress value, which quantifies how well the low-dimensional configuration represents the original distance relationships, with lower stress indicating a better fit. The above analysis resulted in the stress value of 0.12.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="50%">
<col width="50%">
</colgroup>
<thead><tr class="header">
<th align="right">Stress Value</th>
<th>Interpretation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">0.00 - 0.05</td>
<td>Excellent representation; distances in NMDS closely match original dissimilarities</td>
</tr>
<tr class="even">
<td align="right">0.05 - 0.10</td>
<td>Good representation; minor distortions in distances</td>
</tr>
<tr class="odd">
<td align="right">0.10 - 0.20</td>
<td>Fair representation; some distortions present but overall structure interpretable</td>
</tr>
<tr class="even">
<td align="right">0.20 - 0.30</td>
<td>Poor representation; results should be interpreted with caution</td>
</tr>
<tr class="odd">
<td align="right">&gt; 0.30</td>
<td>Very poor representation; ordination is likely unreliable</td>
</tr>
</tbody>
</table></div>
<p>Additionally, the object stores information about the optimization process, including the number of iterations and whether the algorithm successfully converged.</p>
</div>
<div id="visualize-nmds" class="section level4 unnumbered">
<h4>Visualize NMDS<a class="anchor" aria-label="anchor" href="#visualize-nmds"><i class="fas fa-link"></i></a>
</h4>
<p>Often, we are interested in how external factors shape community structure. To explore these relationships, it is helpful to relate the positions of communities in NMDS space to relevant grouping or environmental variables, allowing us to visualize and interpret patterns in community composition.</p>
<p>The dune dataset comes along with environmental data <code>dune.env</code> so we can associate ordination output (whether NMDS, PCoA, or other methods) with site attributes.</p>
<div class="sourceCode" id="cb531"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">dune.env</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dune.env</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    A1 Moisture Management      Use Manure
## 1 2.8        1         SF Haypastu      4
## 2 3.5        1         BF Haypastu      2
## 3 4.3        2         SF Haypastu      4
## 4 4.2        2         SF Haypastu      4
## 5 6.3        1         HF Hayfield      2
## 6 4.3        1         HF Haypastu      2</code></pre>
<p>The <code>dune.env</code> dataset contains 5 environmental variables for the 20 dune meadow sites.</p>
<ul>
<li><p><strong>A1</strong> measures the thickness of the topsoil horizon (top mineral layer).</p></li>
<li><p><strong>Moisture</strong> is an ordered factor indicating soil moisture levels from dry to wet (levels 1, 2, 4, 5).</p></li>
<li><p><strong>Management</strong> is a categorical variable describing the management type: Biological farming (<code>BF</code>), Hobby farming (<code>HF</code>), Nature Conservation Management (<code>NCM</code>), or Standard Farming (<code>SF</code>).</p></li>
<li><p><strong>Use</strong> indicates land-use intensity as an ordered factor from Hayfield to Haypastu to Pasture.</p></li>
<li><p><strong>Manure</strong> is an ordered factor showing manure application levels from 0 to 4.</p></li>
</ul>
<p>In this exercise, we will use the <strong>“Use”</strong> column to investigate whether variations in land-use intensity correspond to differences in plant community composition. The NMDS output stores the coordinates of each site in NMDS space in the <code>$points</code> element, with rows ordered according to the original distance matrix. While you can directly associate site attributes with these coordinates, it is important to ensure that the row order remains consistent to avoid mismatches.</p>
<div class="sourceCode" id="cb533"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Combine environmental data with NMDS coordinates</span></span>
<span><span class="va">df_nmds</span> <span class="op">&lt;-</span> <span class="va">dune.env</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>           <span class="co"># Start with the environmental data for each site</span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>                  <span class="co"># Convert to tibble for tidyverse-friendly operations</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_cols.html">bind_cols</a></span><span class="op">(</span><span class="va">obj_nmds</span><span class="op">$</span><span class="va">points</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>   <span class="co"># Add NMDS coordinates (site scores) as new columns</span></span>
<span>  <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="op">)</span>           <span class="co"># Clean column names (lowercase, replace spaces/special characters)</span></span>
<span></span>
<span><span class="co"># Visualize NMDS site scores with points and 95% confidence ellipses by land-use intensity</span></span>
<span><span class="va">df_nmds</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">mds1</span>,           <span class="co"># NMDS axis 1 (first dimension from metaMDS)</span></span>
<span>    y <span class="op">=</span> <span class="va">mds2</span>,           <span class="co"># NMDS axis 2 (second dimension from metaMDS)</span></span>
<span>    color <span class="op">=</span> <span class="va">use</span>         <span class="co"># Color points by land-use intensity (or other grouping variable)</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>               <span class="co"># Plot each site as a point, slightly larger for visibility</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_ellipse.html">stat_ellipse</a></span><span class="op">(</span>level <span class="op">=</span> <span class="fl">0.95</span>,           <span class="co"># Draw 95% confidence ellipses around each group</span></span>
<span>               linetype <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span>        <span class="co"># Dashed line for ellipse</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>                         <span class="co"># Apply a clean black-and-white theme</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"Land-use intensity"</span>,   <span class="co"># Add a legend title</span></span>
<span>       x <span class="op">=</span> <span class="st">"NMDS1"</span>,                    <span class="co"># Label x-axis</span></span>
<span>       y <span class="op">=</span> <span class="st">"NMDS2"</span><span class="op">)</span>                    <span class="co"># Label y-axis</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:nmds-plot"></span>
<img src="biostats_files/figure-html/nmds-plot-1.png" alt="NMDS ordination of plant communities in the Dutch dune meadows dataset (`dune`), with sites colored by land-use intensity (`Use`). The plot visualizes differences in community composition among sites along the first two NMDS axes." width="672"><p class="caption">
Figure 19.4: NMDS ordination of plant communities in the Dutch dune meadows dataset (<code>dune</code>), with sites colored by land-use intensity (<code>Use</code>). The plot visualizes differences in community composition among sites along the first two NMDS axes.
</p>
</div>
<p>From the NMDS plot, it appears that sites with different land-use intensities might occupy slightly different regions in ordination space, suggesting potential differences in plant community composition. While visual inspection provides a useful first impression, we need a formal statistical test to determine whether these apparent group differences are significant.</p>
</div>
<div id="test-with-permanova" class="section level4 unnumbered">
<h4>Test with PERMANOVA<a class="anchor" aria-label="anchor" href="#test-with-permanova"><i class="fas fa-link"></i></a>
</h4>
<p>To formally test whether plant community composition differs among levels of land-use intensity, we can use PERMANOVA (Permutational Multivariate Analysis of Variance).</p>
<p>Unlike traditional MANOVA, PERMANOVA does not assume multivariate normality and can be applied directly to a distance or dissimilarity matrix, such as the Bray-Curtis distances used in the NMDS analysis.</p>
<p>This approach assesses whether the centroids of groups—here, the categories of the “<strong>Use</strong>” variable—differ significantly in multivariate space. The <code>adonis2()</code> function from the <code>vegan</code> package can be used to perform this analysis, testing whether plant community composition differs among groups based on a chosen environmental factor.</p>
<div class="sourceCode" id="cb534"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Perform PERMANOVA to test whether plant community composition differs by land-use intensity</span></span>
<span><span class="fu">adonis2</span><span class="op">(</span></span>
<span>  <span class="va">m_bray</span> <span class="op">~</span> <span class="va">use</span>,   <span class="co"># Model formula: Bray-Curtis dissimilarities (m_bray) explained by 'use' factor</span></span>
<span>  data <span class="op">=</span> <span class="va">df_nmds</span>  <span class="co"># Data frame containing the grouping variable 'use' aligned with the distance matrix</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>## Permutation test for adonis under reduced model
## Terms added sequentially (first to last)
## Permutation: free
## Number of permutations: 999
## 
## adonis2(formula = m_bray ~ use, data = df_nmds)
##          Df SumOfSqs      R2      F Pr(&gt;F)
## use       2   0.5532 0.12867 1.2552  0.252
## Residual 17   3.7459 0.87133              
## Total    19   4.2990 1.00000</code></pre>
<p>We used PERMANOVA to test whether plant communities differ among the three land-use intensity categories (<code>use</code>). This method looks at the overall differences in species composition between groups and compares them to differences within groups. In our analysis, land-use intensity explains about 13% of the variation in plant communities, while the remaining 87% comes from other factors or natural variation (column <code>R2</code>).</p>
<p>The test gave a p-value of 0.258, which means the differences we see are <strong>not statistically significant</strong>. In simple terms, even though the NMDS plot shows some separation between sites with different land-use intensity, the test suggests that these differences could easily have happened by chance. So, we do not have strong evidence that land-use intensity alone drives changes in plant community composition in this dataset.</p>
</div>
</div>
<div id="other-options" class="section level3" number="19.1.3">
<h3>
<span class="header-section-number">19.1.3</span> Other Options<a class="anchor" aria-label="anchor" href="#other-options"><i class="fas fa-link"></i></a>
</h3>
<p>There are many options for unconstrained ordination, and we have explored two extremes. PCA preserves the most quantitative information from the original variables, but it comes with strict assumptions, including linearity and normality. In contrast, NMDS is highly flexible and applicable to a wide range of multivariate data, but it only preserves qualitative, ranked information in the reduced dimensions.</p>
<p>Other ordination methods fall somewhere between these two approaches. For example, Principal Coordinates Analysis (PCoA) can accommodate a variety of distance metrics; Correspondence Analysis (CA) is designed for categorical or count data, rather than continuous variables. Selecting the appropriate method depends on the type and distribution of the data as well as the specific ecological questions being addressed.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="25%">
<col width="25%">
<col width="25%">
<col width="25%">
</colgroup>
<thead><tr class="header">
<th>Method</th>
<th>Advantage</th>
<th>Limitation</th>
<th>Example Applications</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>PCA (Principal Component Analysis)</strong></td>
<td>Preserves maximum quantitative variation; easy to interpret; widely used</td>
<td>Assumes linear relationships and roughly normal distribution; sensitive to outliers</td>
<td>Continuous trait data, environmental gradients, physiological measurements</td>
</tr>
<tr class="even">
<td><strong>PCoA (Principal Coordinates Analysis)</strong></td>
<td>Can use any distance or dissimilarity metric; preserves distances as well as possible</td>
<td>May produce negative eigenvalues if data not Euclidean; interpretation depends on metric chosen</td>
<td>Community ecology, phylogenetic distances, functional trait distances</td>
</tr>
<tr class="odd">
<td><strong>CA (Correspondence Analysis)</strong></td>
<td>Works directly on count data; simultaneously ordinates sites and species; produces interpretable eigenvalues</td>
<td>Designed for count/abundance data rather than continuous variables; can produce “arch effect” with long gradients</td>
<td>Species-by-site abundance matrices, ecological community composition</td>
</tr>
<tr class="even">
<td><strong>MCA (Multiple Correspondence Analysis)</strong></td>
<td>Reduces dimensionality of multiple categorical variables; reveals patterns and associations among categories</td>
<td>Requires categorical variables; can be computationally intensive with many categories; interpretation requires understanding of dummy coding</td>
<td>Survey data with multiple choice questions, demographic patterns, clinical categorical variables, questionnaire analysis</td>
</tr>
<tr class="odd">
<td><strong>NMDS (Non-metric Multidimensional Scaling)</strong></td>
<td>Very flexible; works with many data types and dissimilarity metrics; handles non-linear patterns and long gradients well</td>
<td>Only preserves rank-order information; axes not directly interpretable in units of original variables; requires multiple runs</td>
<td>Ecological community data with skewed or zero-inflated abundances; species composition comparisons</td>
</tr>
</tbody>
</table></div>
</div>
<div id="axis-interpretability" class="section level3" number="19.1.4">
<h3>
<span class="header-section-number">19.1.4</span> Axis Interpretability<a class="anchor" aria-label="anchor" href="#axis-interpretability"><i class="fas fa-link"></i></a>
</h3>
<p>One key difference among ordination methods lies in the interpretability of the axes themselves. Methods can be broadly categorized into those with <strong>directly interpretable axes</strong> and those with <strong>abstract distance-based axes</strong>.</p>
<p><strong>PCA, CA, and MCA</strong> produce axes that are meaningful transformations of the original data:</p>
<ul>
<li><p><strong>PCA</strong>: The axes (principal components) are linear combinations of the original variables, so the coordinates along each axis are meaningful and can be interpreted in terms of the original measurements. For example, higher values on PC1 may reflect larger trait values or abundances across species. Each axis explains a specific percentage of the total variance, and loadings show how original variables contribute to each component.</p></li>
<li><p><strong>CA</strong>: The axes are weighted averages of species scores (for sites) and site scores (for species), with units in standard deviations of species turnover. Sites with similar species composition cluster together, and the position along each axis reflects species compositional change. Eigenvalues indicate the strength of each axis in capturing species turnover.</p></li>
<li><p><strong>MCA</strong>: Similar to PCA but for categorical data, the axes represent dimensions of variation among categorical variables. Coordinates reflect the association strength with particular categories, and contributions of each category to each dimension can be quantified.</p></li>
</ul>
<p><strong>PCoA and NMDS</strong> create axes in arbitrary units where only relative positions matter:</p>
<ul>
<li><p><strong>PCoA</strong>: Axes preserve the distances between samples as faithfully as possible based on the chosen distance metric. The axes themselves are in arbitrary units, but eigenvalues show how much of the total distance variation each axis captures. The interpretation depends entirely on which distance metric was used (e.g., Bray-Curtis, UniFrac).</p></li>
<li><p><strong>NMDS</strong>: Axes are purely abstract dimensions constructed to best preserve the rank order of dissimilarities between sites. The numeric values along NMDS axes do not have inherent meaning; only the relative distances between points matter. Unlike PCoA, NMDS doesn’t even preserve exact distances—only their rank order. As a result, NMDS plots are interpreted in terms of patterns of similarity or separation among sites, not in terms of the absolute values on each axis. The quality of fit is measured by stress values rather than variance explained.</p></li>
</ul>
<p><strong>Practical implication</strong>: For methods with interpretable axes (PCA, CA, MCA), you can meaningfully describe what high or low values on an axis represent. For distance-based methods (PCoA, NMDS), you can only describe which samples are similar or dissimilar to each other.</p>
</div>
</div>
<div id="laboratory-12" class="section level2" number="19.2">
<h2>
<span class="header-section-number">19.2</span> Laboratory<a class="anchor" aria-label="anchor" href="#laboratory-12"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="generalized-additive-model.html"><span class="header-section-number">18</span> Generalized Additive Model</a></div>
<div class="next"><a href="constrained-ordination.html"><span class="header-section-number">20</span> Constrained Ordination</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#unconstrained-ordination"><span class="header-section-number">19</span> Unconstrained Ordination</a></li>
<li>
<a class="nav-link" href="#methods-for-unconstrained-ordination"><span class="header-section-number">19.1</span> Methods for Unconstrained Ordination</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#pca"><span class="header-section-number">19.1.1</span> PCA</a></li>
<li><a class="nav-link" href="#nmds"><span class="header-section-number">19.1.2</span> NMDS</a></li>
<li><a class="nav-link" href="#other-options"><span class="header-section-number">19.1.3</span> Other Options</a></li>
<li><a class="nav-link" href="#axis-interpretability"><span class="header-section-number">19.1.4</span> Axis Interpretability</a></li>
</ul>
</li>
<li><a class="nav-link" href="#laboratory-12"><span class="header-section-number">19.2</span> Laboratory</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/aterui/biostats/blob/master/chapters/adv-03-uord.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/aterui/biostats/edit/master/chapters/adv-03-uord.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BIOSTATS</strong>" was written by Akira Terui. It was last built on 2025-12-22.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
